HEADING_TYPE_CHOICES = [
	("h2","H2"),
	("h3","H3"),
	("h4","H4"),
	("h5","H5"),
	("h6","H6"),
]

FLOATING_CHOICE = [
	("right", "Right"),
	("center", "Center"),
	("left", "Left"),
]

SIZE_CHOICE = [
	('s', 'Small'),
	('m', 'Medium'),
	('l', 'Large'),
]

# DELETE, I have the model 'LinkRelationtship' class to store this
LINKS_TYPE_CHOICE = [
	("follow", "follow"),
	("nofollow", "nofollow"),
	("ugc", "ugc"),		# Enlaces donde los usuarios puedan crear contenido propio, foros y comentarios, etc.
	("sponsored", "sponsored"),		# Todos los enlaces que son parte de una acción publicitaria
	("noreferrer", "noreferrer"),		# Hides referrer info when the link is clicked
	("noopener", "noopener"),		# This is useful whene opening untrusted links
]

META_ROBOTS_CHOICE = [
	("index, folllow","Index, Follow"),
	("index, nofollow","Index, Nofollow"),
	("noindex, follow","Noindex, Follow"),
	("noindex, nofollow","Noindex, Nofollow"),
]

META_LANGUAGES = [
    ('en', "English"),
    ('es', "Español"),
    ('fr', "Français"),
    ('de', "Deutsch"),
    ('nl', "Nederlands"),
    ('pt', "Portuguese"),
]

SOCIALLINKS_CHOICES = [
	('5px', '500px'),
	('Fc', 'Facebook'),
	('4sq', 'FourSquare'),
	('Flk', 'Flickr'),
	('Gth', 'GitHub'),
	('Gtl', 'GitLab'),
	('Gpl', 'Google+'),
	('Ig', 'Instagram'),
	('Li', 'LinkedIn'),
	('Pt', 'Pinterest'),
	('Ptr', 'Patreon'),
	('Snp', 'Snapchat'),
	('Spy', 'Spotify'),
	('Scl', 'SoundCloud'),
	('Tw', 'Twitter'),
	('Vm', 'Vimeo'),
	('Xi', 'Xing'),
	('Yp', 'Yelp'),
	('Yt', 'YouTube'),
]
	
ICON_CHOICES_EN = [
	("fab fa-500px","fab fa-500px"),
	("fab fa-accessible-icon","fab fa-accessible-icon"),
	("fab fa-accusoft","fab fa-accusoft"),
	("fab fa-acquisitions-incorporated","fab fa-acquisitions-incorporated"),
	("fab fa-adn","fab fa-adn"),
	("fab fa-adobe","fab fa-adobe"),
	("fab fa-adversal","fab fa-adversal"),
	("fab fa-affiliatetheme","fab fa-affiliatetheme"),
	("fab fa-airbnb","fab fa-affiliatetheme"),
	("fab fa-algolia","fab fa-algolia"),
	("fab fa-alipay","fab fa-alipay"),
	("fab fa-amazon","fab fa-amazon"),
	("fab fa-amazon-pay","fab fa-amazon-pay"),
	("fab fa-amilia","fab fa-amilia"),
	("fab fa-android","fab fa-android"),
	("fab fa-angellist","fab fa-angellist"),
	("fab fa-angrycreative","fab fa-angrycreative"),
	("fab fa-angular","fab fa-angular"),
	("fab fa-app-store","fab fa-app-store"),
	("fab fa-app-store-ios","fab fa-app-store-ios"),
	("fab fa-apper","fab fa-apper"),
	("fab fa-apple","fab fa-apple"),
	("fab fa-apple-pay","fab fa-apple-pay"),
	("fab fa-audible","fab fa-audible"),
	("fab fa-artstation","fab fa-artstation"),
	("fab fa-asymmetrik","fab fa-asymmetrik"),
	("fab fa-atlassian","fab fa-atlassian"),
	("fab fa-avianex","fab fa-avianex"),
	("fab fa-airbnb","fab fa-airbnb"),
	("fab fa-aviato","fab fa-aviato"),
	("fab fa-aws","fab fa-aws"),
	("fab fa-bandcamp","fab fa-bandcamp"),
	("fab fa-battle-net","fab fa-battle-net"),
	("fab fa-behance","fab fa-behance"),
	("fab fa-behance-square","fab fa-behance-square"),
	("fab fa-bimobject","fab fa-bimobject"),
	("fab fa-bitbucket","fab fa-bitbucket"),
	("fab fa-bitcoin","fab fa-bitcoin"),
	("fab fa-bity","fab fa-bity"),
	("fab fa-black-tie","fab fa-black-tie"),
	("fab fa-blackberry","fab fa-blackberry"),
	("fab fa-blogger","fab fa-blogger"),
	("fab fa-blogger-b","fab fa-blogger-b"),
	("fab fa-bluetooth","fab fa-bluetooth"),
	("fab fa-bluetooth-b","fab fa-bluetooth-b"),
	("fab fa-bootstrap","fab fa-bootstrap"),
	("fab fa-btc","fab fa-btc"),
	("fab fa-buffer","fab fa-buffer"),
	("fab fa-buromobelexperte","fab fa-buromobelexperte"),
	("fab fa-buy-n-large","fab fa-buy-n-large"),
	("fab fa-buysellads","fab fa-buysellads"),
	("fab fa-canadian-maple-leaf","fab fa-canadian-maple-leaf"),
	("fab fa-cc-amazon-pay","fab fa-cc-amazon-pay"),
	("fab fa-cc-amex","fab fa-cc-amex"),
	("fab fa-cc-apple-pay","fab fa-cc-apple-pay"),
	("fab fa-cc-diners-club","fab fa-cc-diners-club"),
	("fab fa-cc-discover","fab fa-cc-discover"),
	("fab fa-cc-jcb","fab fa-cc-jcb"),
	("fab fa-cc-mastercard","fab fa-cc-mastercard"),
	("fab fa-cc-paypal","fab fa-cc-paypal"),
	("fab fa-cc-stripe","fab fa-cc-stripe"),
	("fab fa-cc-visa","fab fa-cc-visa"),
	("fab fa-centercode","fab fa-centercode"),
	("fab fa-centos","fab fa-centos"),
	("fab fa-chrome","fab fa-chrome"),
	("fab fa-chromecast","fab fa-chromecast"),
	("fab fa-cloudscale","fab fa-cloudscale"),
	("fab fa-cloudsmith","fab fa-cloudsmith"),
	("fab fa-cloudversify","fab fa-cloudversify"),
	("fab fa-codepen","fab fa-codepen"),
	("fab fa-codiepie","fab fa-codiepie"),
	("fab fa-confluence","fab fa-confluence"),
	("fab fa-connectdevelop","fab fa-connectdevelop"),
	("fab fa-contao","fab fa-contao"),
	("fab fa-cotton-bureau","fab fa-cotton-bureau"),
	("fab fa-cpanel","fab fa-cpanel"),
	("fab fa-creative-commons","fab fa-creative-commons"),
	("fab fa-creative-commons-by","fab fa-creative-commons-by"),
	("fab fa-creative-commons-nc","fab fa-creative-commons-nc"),
	("fab fa-creative-commons-nc-eu","fab fa-creative-commons-nc-eu"),
	("fab fa-creative-commons-nc-jp","fab fa-creative-commons-nc-jp"),
	("fab fa-creative-commons-nd","fab fa-creative-commons-nd"),
	("fab fa-creative-commons-pd","fab fa-creative-commons-pd"),
	("fab fa-creative-commons-pd-alt","fab fa-creative-commons-pd-alt"),
	("fab fa-creative-commons-remix","fab fa-creative-commons-remix"),
	("fab fa-creative-commons-sa","fab fa-creative-commons-sa"),
	("fab fa-creative-commons-sampling","fab fa-creative-commons-sampling"),
	("fab fa-creative-commons-sampling-plus","fab fa-creative-commons-sampling-plus"),
	("fab fa-creative-commons-share","fab fa-creative-commons-share"),
	("fab fa-creative-commons-zero","fab fa-creative-commons-zero"),
	("fab fa-critical-role","fab fa-critical-role"),
	("fab fa-css3","fab fa-css3"),
	("fab fa-css3-alt","fab fa-css3-alt"),
	("fab fa-cuttlefish","fab fa-cuttlefish"),
	("fab fa-d-and-d","fab fa-d-and-d"),
	("fab fa-d-and-d-beyond","fab fa-d-and-d-beyond"),
	("fab fa-dailymotion","fab fa-dailymotion"),
	("fab fa-dashcube","fab fa-dashcube"),
	("fab fa-delicious","fab fa-delicious"),
	("fab fa-deploydog","fab fa-deploydog"),
	("fab fa-deskpro","fab fa-deskpro"),
	("fab fa-dev","fab fa-dev"),
	("fab fa-deviantart","fab fa-deviantart"),
	("fab fa-dhl","fab fa-dhl"),
	("fab fa-diaspora","fab fa-diaspora"),
	("fab fa-digg","fab fa-digg"),
	("fab fa-digital-ocean","fab fa-digital-ocean"),
	("fab fa-discord","fab fa-discord"),
	("fab fa-discourse","fab fa-discourse"),
	("fab fa-dochub","fab fa-dochub"),
	("fab fa-docker","fab fa-docker"),
	("fab fa-draft2digital","fab fa-draft2digital"),
	("fab fa-dribbble","fab fa-dribbble"),
	("fab fa-dribbble-square","fab fa-dribbble-square"),
	("fab fa-dropbox","fab fa-dropbox"),
	("fab fa-elementor","fab fa-elementor"),
	("fab fa-drupal","fab fa-drupal"),
	("fab fa-dyalog","fab fa-dyalog"),
	("fab fa-earlybirds","fab fa-earlybirds"),
	("fab fa-ebay","fab fa-ebay"),
	("fab fa-edge","fab fa-edge"),
	("fab fa-ello","fab fa-ello"),
	("fab fa-ember","fab fa-ember"),
	("fab fa-empire","fab fa-empire"),
	("fab fa-envira","fab fa-envira"),
	("fab fa-erlang","fab fa-erlang"),
	("fab fa-ethereum","fab fa-ethereum"),
	("fas fa-autoprefixer","fas fa-autoprefixer"),
	("fas fa-ad","fas fa-ad"),
	("fas fa-address-book","fas fa-address-book"),
	("fas fa-address-card","fas fa-address-card"),
	("fas fa-adjust","fas fa-adjust"),
	("fas fa-air-freshener","fas fa-air-freshener"),
	("fas fa-align-center","fas fa-align-center"),
	("fas fa-align-justify","fas fa-align-justify"),
	("fas fa-align-left","fas fa-align-left"),
	("fas fa-align-right","fas fa-align-right"),
	("fas fa-allergies","fas fa-allergies"),
	("fas fa-ambulance","fas fa-ambulance"),
	("fas fa-american-sign-language-interpreting","fas fa-american-sign-language-interpreting"),
	("fas fa-anchor","fas fa-anchor"),
	("fas fa-angle-double-down","fas fa-angle-double-down"),
	("fas fa-angle-double-left","fas fa-angle-double-left"),
	("fas fa-angle-double-right","fas fa-angle-double-right"),
	("fas fa-angle-double-up","fas fa-angle-double-up"),
	("fas fa-angle-down","fas fa-angle-down"),
	("fas fa-angle-up","fas fa-angle-up"),
	("fas fa-angle-left","fas fa-angle-left"),
	("fas fa-angle-right","fas fa-angle-right"),
	("fas fa-angry","fas fa-angry"),
	("fas fa-ankh","fas fa-ankh"),
	("fas fa-apple-alt","fas fa-apple-alt"),
	("fas fa-archive","fas fa-archive"),
	("fas fa-archway","fas fa-archway"),
	("fas fa-arrow-alt-circle-down","fas fa-arrow-alt-circle-down"),
	("fas fa-arrow-alt-circle-left","fas fa-arrow-alt-circle-left"),
	("fas fa-arrow-alt-circle-up","fas fa-arrow-alt-circle-up"),
	("fas fa-arrow-alt-circle-right","fas fa-arrow-alt-circle-right"),
	("fas fa-arrow-circle-down","fas fa-arrow-circle-down"),
	("fas fa-arrow-circle-up","fas fa-arrow-circle-up"),
	("fas fa-arrow-circle-left","fas fa-arrow-circle-left"),
	("fas fa-arrow-circle-right","fas fa-arrow-circle-right"),
	("fas fa-arrow-down","fas fa-arrow-down"),
	("fas fa-arrow-up","fas fa-arrow-up"),
	("fas fa-arrow-left","fas fa-arrow-left"),
	("fas fa-arrow-right","fas fa-arrow-right"),
	("fas fa-arrows-alt","fas fa-arrows-alt"),
	("fas fa-arrows-alt-h","fas fa-arrows-alt-h"),
	("fas fa-arrows-alt-v","fas fa-arrows-alt-v"),
	("fas fa-assistive-listening-systems","fas fa-assistive-listening-systems"),
	("fas fa-asterisk","fas fa-asterisk"),
	("fas fa-at","fas fa-at"),
	("fas fa-atlas","fas fa-atlas"),
	("fas fa-atom","fas fa-atom"),
	("fas fa-audio-description","fas fa-audio-description"),
	("fas fa-award","fas fa-award"),
	("fas fa-baby","fas fa-baby"),
	("fas fa-baby-carriage","fas fa-baby-carriage"),
	("fas fa-backspace","fas fa-backspace"),
	("fas fa-backward","fas fa-backward"),
	("fas fa-bacon","fas fa-bacon"),
	("fas fa-bahai","fas fa-bahai"),
	("fas fa-balance-scale","fas fa-balance-scale"),
	("fas fa-balance-scale-left","fas fa-balance-scale-left"),
	("fas fa-balance-scale-right","fas fa-balance-scale-right"),
	("fas fa-ban","fas fa-ban"),
	("fas fa-band-aid","fas fa-band-aid"),
	("fas fa-barcode","fas fa-barcode"),
	("fas fa-bars","fas fa-bars"),
	("fas fa-baseball-ball","fas fa-baseball-ball"),
	("fas fa-basketball-ball","fas fa-basketball-ball"),
	("fas fa-bath","fas fa-bath"),
	("fas fa-battery-empty","fas fa-battery-empty"),
	("fas fa-battery-half","fas fa-battery-half"),
	("fas fa-battery-full","fas fa-battery-full"),
	("fas fa-battery-quarter","fas fa-battery-quarter"),
	("fas fa-battery-three-quarters","fas fa-battery-three-quarters"),
	("fas fa-bed","fas fa-bed"),
	("fas fa-beer","fas fa-beer"),
	("fas fa-bell","fas fa-bell"),
	("fas fa-bell-slash","fas fa-bell-slash"),
	("fas fa-bezier-curve","fas fa-bezier-curve"),
	("fas fa-bible","fas fa-bible"),
	("fas fa-bicycle","fas fa-bicycle"),
	("fas fa-biking","fas fa-biking"),
	("fas fa-binoculars","fas fa-binoculars"),
	("fas fa-biohazard","fas fa-biohazard"),
	("fas fa-birthday-cake","fas fa-birthday-cake"),
	("fas fa-blender","fas fa-blender"),
	("fas fa-blind","fas fa-blind"),
	("fas fa-blog","fas fa-blog"),
	("fas fa-bold","fas fa-bold"),
	("fas fa-bolt","fas fa-bolt"),
	("fas fa-bomb","fas fa-bomb"),
	("fas fa-bone","fas fa-bone"),
	("fas fa-book","fas fa-book"),
	("fas fa-bong","fas fa-bong"),
	("fas fa-book-dead","fas fa-book-dead"),
	("fas fa-book-medical","fas fa-book-medical"),
	("fas fa-book-open","fas fa-book-open"),
	("fas fa-book-reader","fas fa-book-reader"),
	("fas fa-bookmark","fas fa-bookmark"),
	("fas fa-border-all","fas fa-border-all"),
	("fas fa-border-none","fas fa-border-none"),
	("fas fa-border-style","fas fa-border-style"),
	("fas fa-bowling-ball","fas fa-bowling-ball"),
	("fas fa-box","fas fa-box"),
	("fas fa-box-open","fas fa-box-open"),
	("fas fa-box-tissue","fas fa-box-tissue"),
	("fas fa-boxes","fas fa-boxes"),
	("fas fa-braille","fas fa-braille"),
	("fas fa-brain","fas fa-brain"),
	("fas fa-bread-slice","fas fa-bread-slice"),
	("fas fa-briefcase","fas fa-briefcase"),
	("fas fa-briefcase-medical","fas fa-briefcase-medical"),
	("fas fa-broadcast-tower","fas fa-broadcast-tower"),
	("fas fa-broom","fas fa-broom"),
	("fas fa-brush","fas fa-brush"),
	("fas fa-bug","fas fa-bug"),
	("fas fa-building","fas fa-building"),
	("fas fa-bullhorn","fas fa-bullhorn"),
	("fas fa-bullseye","fas fa-bullseye"),
	("fas fa-burn","fas fa-burn"),
	("fas fa-bus","fas fa-bus"),
	("fas fa-bus-alt","fas fa-bus-alt"),
	("fas fa-business-time","fas fa-business-time"),
	("fas fa-calculator","fas fa-calculator"),
	("fas fa-calendar","fas fa-calendar"),
	("fas fa-calendar-alt","fas fa-calendar-alt"),
	("fas fa-calendar-check","fas fa-calendar-check"),
	("fas fa-calendar-day","fas fa-calendar-day"),
	("fas fa-calendar-minus","fas fa-calendar-minus"),
	("fas fa-calendar-plus","fas fa-calendar-plus"),
	("fas fa-calendar-times","fas fa-calendar-times"),
	("fas fa-calendar-week","fas fa-calendar-week"),
	("fas fa-camera","fas fa-camera"),
	("fas fa-camera-retro","fas fa-camera-retro"),
	("fas fa-campground","fas fa-campground"),
	("fas fa-candy-cane","fas fa-candy-cane"),
	("fas fa-cannabis","fas fa-cannabis"),
	("fas fa-capsules","fas fa-capsules"),
	("fas fa-car","fas fa-car"),
	("fas fa-car-alt","fas fa-car-alt"),
	("fas fa-car-battery","fas fa-car-battery"),
	("fas fa-car-crash","fas fa-car-crash"),
	("fas fa-car-side","fas fa-car-side"),
	("fas fa-caravan","fas fa-caravan"),
	("fas fa-caret-down","fas fa-caret-down"),
	("fas fa-caret-left","fas fa-caret-left"),
	("fas fa-caret-right","fas fa-caret-right"),
	("fas fa-caret-square-down","fas fa-caret-square-down"),
	("fas fa-caret-square-left","fas fa-caret-square-left"),
	("fas fa-caret-square-right","fas fa-caret-square-right"),
	("fas fa-caret-square-up","fas fa-caret-square-up"),
	("fas fa-caret-up","fas fa-caret-up"),
	("fas fa-carrot","fas fa-carrot"),
	("fas fa-cart-arrow-down","fas fa-cart-arrow-down"),
	("fas fa-cart-plus","fas fa-cart-plus"),
	("fas fa-cash-register","fas fa-cash-register"),
	("fas fa-cat","fas fa-cat"),
	("fas fa-certificate","fas fa-certificate"),
	("fas fa-chair","fas fa-chair"),
	("fas fa-chalkboard","fas fa-chalkboard"),
	("fas fa-chalkboard-teacher","fas fa-chalkboard-teacher"),
	("fas fa-charging-station","fas fa-charging-station"),
	("fas fa-chart-area","fas fa-chart-area"),
	("fas fa-chart-bar","fas fa-chart-bar"),
	("fas fa-chart-line","fas fa-chart-line"),
	("fas fa-chart-pie","fas fa-chart-pie"),
	("fas fa-check","fas fa-check"),
	("fas fa-check-circle","fas fa-check-circle"),
	("fas fa-check-double","fas fa-check-double"),
	("fas fa-check-square","fas fa-check-square"),
	("fas fa-cheese","fas fa-cheese"),
	("fas fa-chess","fas fa-chess"),
	("fas fa-chess-bishop","fas fa-chess-bishop"),
	("fas fa-chess-board","fas fa-chess-board"),
	("fas fa-chess-king","fas fa-chess-king"),
	("fas fa-chess-knight","fas fa-chess-knight"),
	("fas fa-chess-pawn","fas fa-chess-pawn"),
	("fas fa-chess-queen","fas fa-chess-queen"),
	("fas fa-chess-rook","fas fa-chess-rook"),
	("fas fa-chevron-circle-down","fas fa-chevron-circle-down"),
	("fas fa-chevron-circle-left","fas fa-chevron-circle-left"),
	("fas fa-chevron-circle-right","fas fa-chevron-circle-right"),
	("fas fa-chevron-circle-up","fas fa-chevron-circle-up"),
	("fas fa-chevron-down","fas fa-chevron-down"),
	("fas fa-chevron-left","fas fa-chevron-left"),
	("fas fa-chevron-right","fas fa-chevron-right"),
	("fas fa-chevron-up","fas fa-chevron-up"),
	("fas fa-child","fas fa-child"),
	("fas fa-church","fas fa-church"),
	("fas fa-circle","fas fa-circle"),
	("fas fa-circle-notch","fas fa-circle-notch"),
	("fas fa-city","fas fa-city"),
	("fas fa-clinic-medical","fas fa-clinic-medical"),
	("fas fa-clipboard","fas fa-clipboard"),
	("fas fa-clipboard-check","fas fa-clipboard-check"),
	("fas fa-clipboard-list","fas fa-clipboard-list"),
	("fas fa-clock","fas fa-clock"),
	("fas fa-clone","fas fa-clone"),
	("fas fa-closed-captioning","fas fa-closed-captioning"),
	("fas fa-cloud","fas fa-cloud"),
	("fas fa-cloud-download-alt","fas fa-cloud-download-alt"),
	("fas fa-cloud-meatball","fas fa-cloud-meatball"),
	("fas fa-cloud-moon","fas fa-cloud-moon"),
	("fas fa-cloud-moon-rain","fas fa-cloud-moon-rain"),
	("fas fa-cloud-rain","fas fa-cloud-rain"),
	("fas fa-cloud-showers-heavy","fas fa-cloud-showers-heavy"),
	("fas fa-cloud-sun","fas fa-cloud-sun"),
	("fas fa-cloud-sun-rain","fas fa-cloud-sun-rain"),
	("fas fa-cloud-upload-alt","fas fa-cloud-upload-alt"),
	("fas fa-cocktail","fas fa-cocktail"),
	("fas fa-code","fas fa-code"),
	("fas fa-code-branch","fas fa-code-branch"),
	("fas fa-coffee","fas fa-coffee"),
	("fas fa-cog","fas fa-cog"),
	("fas fa-cogs","fas fa-cogs"),
	("fas fa-coins","fas fa-coins"),
	("fas fa-columns","fas fa-columns"),
	("fas fa-comment","fas fa-comment"),
	("fas fa-comment-alt","fas fa-comment-alt"),
	("fas fa-comment-dollar","fas fa-comment-dollar"),
	("fas fa-comment-dots","fas fa-comment-dots"),
	("fas fa-comment-medical","fas fa-comment-medical"),
	("fas fa-comment-slash","fas fa-comment-slash"),
	("fas fa-comments","fas fa-comments"),
	("fas fa-comments-dollar","fas fa-comments-dollar"),
	("fas fa-compact-disc","fas fa-compact-disc"),
	("fas fa-compass","fas fa-compass"),
	("fas fa-compress","fas fa-compress"),
	("fas fa-compress-alt","fas fa-compress-alt"),
	("fas fa-compress-arrows-alt","fas fa-compress-arrows-alt"),
	("fas fa-concierge-bell","fas fa-concierge-bell"),
	("fas fa-cookie","fas fa-cookie"),
	("fas fa-cookie-bite","fas fa-cookie-bite"),
	("fas fa-copy","fas fa-copy"),
	("fas fa-copyright","fas fa-copyright"),
	("fas fa-couch","fas fa-couch"),
	("fas fa-credit-card","fas fa-credit-card"),
	("fas fa-crop","fas fa-crop"),
	("fas fa-crop-alt","fas fa-crop-alt"),
	("fas fa-cross","fas fa-cross"),
	("fas fa-crosshairs","fas fa-crosshairs"),
	("fas fa-crow","fas fa-crow"),
	("fas fa-crown","fas fa-crown"),
	("fas fa-crutch","fas fa-crutch"),
	("fas fa-cube","fas fa-cube"),
	("fas fa-cubes","fas fa-cubes"),
	("fas fa-cut","fas fa-cut"),
	("fas fa-dailymotion","fas fa-dailymotion"),
	("fas fa-database","fas fa-database"),
	("fas fa-deaf","fas fa-deaf"),
	("fas fa-democrat","fas fa-democrat"),
	("fas fa-desktop","fas fa-desktop"),
	("fas fa-dharmachakra","fas fa-dharmachakra"),
	("fas fa-diagnoses","fas fa-diagnoses"),
	("fas fa-dice","fas fa-dice"),
	("fas fa-dice-d20","fas fa-dice-d20"),
	("fas fa-dice-d6","fas fa-dice-d6"),
	("fas fa-dice-five","fas fa-dice-five"),
	("fas fa-dice-four","fas fa-dice-four"),
	("fas fa-dice-one","fas fa-dice-one"),
	("fas fa-dice-six","fas fa-dice-six"),
	("fas fa-dice-three","fas fa-dice-three"),
	("fas fa-dice-two","fas fa-dice-two"),
	("fas fa-digital-tachograph","fas fa-digital-tachograph"),
	("fas fa-directions","fas fa-directions"),
	("fas fa-disease","fas fa-disease"),
	("fas fa-divide","fas fa-divide"),
	("fas fa-dizzy","fas fa-dizzy"),
	("fas fa-dna","fas fa-dna"),
	("fas fa-dog","fas fa-dog"),
	("fas fa-dollar-sign","fas fa-dollar-sign"),
	("fas fa-dolly","fas fa-dolly"),
	("fas fa-dolly-flatbed","fas fa-dolly-flatbed"),
	("fas fa-donate","fas fa-donate"),
	("fas fa-door-closed","fas fa-door-closed"),
	("fas fa-door-open","fas fa-door-open"),
	("fas fa-dot-circle","fas fa-dot-circle"),
	("fas fa-dove","fas fa-dove"),
	("fas fa-download","fas fa-download"),
	("fas fa-drafting-compass","fas fa-drafting-compass"),
	("fas fa-dragon","fas fa-dragon"),
	("fas fa-draw-polygon","fas fa-draw-polygon"),
	("fas fa-drum","fas fa-drum"),
	("fas fa-drum-steelpan","fas fa-drum-steelpan"),
	("fas fa-drumstick-bite","fas fa-drumstick-bite"),
	("fas fa-dumbbell","fas fa-dumbbell"),
	("fas fa-dumpster","fas fa-dumpster"),
	("fas fa-dumpster-fire","fas fa-dumpster-fire"),
	("fas fa-dungeon","fas fa-dungeon"),
	("fas fa-edit","fas fa-edit"),
	("fas fa-egg","fas fa-egg"),
	("fas fa-eject","fas fa-eject"),
	("fas fa-ellipsis-h","fas fa-ellipsis-h"),
	("fas fa-ellipsis-v","fas fa-ellipsis-v"),
	("fas fa-envelope","fas fa-envelope"),
	("fas fa-envelope-open","fas fa-envelope-open"),
	("fas fa-envelope-open-text","fas fa-envelope-open-text"),
	("fas fa-envelope-square","fas fa-envelope-square"),
	("fas fa-equals","fas fa-equals"),
	("fas fa-eraser","fas fa-eraser"),
	("fas fa-ethernet","fas fa-ethernet"),
	("fas fa-euro-sign","fas fa-euro-sign"),
	("fab fa-etsy","fab fa-etsy"),
	("fab fa-evernote","fab fa-evernote"),
	("fas fa-exchange-alt","fas fa-exchange-alt"),
	("fas fa-exclamation","fas fa-exclamation"),
	("fas fa-exclamation-circle","fas fa-exclamation-circle"),
	("fas fa-exclamation-triangle","fas fa-exclamation-triangle"),
	("fas fa-expand","fas fa-expand"),
	("fas fa-expand-alt","fas fa-expand-alt"),
	("fas fa-expand-arrows-alt","fas fa-expand-arrows-alt"),
	("fab fa-expeditedssl","fab fa-expeditedssl"),
	("fas fa-external-link-alt","fas fa-external-link-alt"),
	("fas fa-external-link-square-alt","fas fa-external-link-square-alt"),
	("fas fa-eye","fas fa-eye"),
	("fas fa-eye-dropper","fas fa-eye-dropper"),
	("fas fa-eye-slash","fas fa-eye-slash"),
	("fab fa-facebook","fab fa-facebook"),
	("fab fa-facebook-f","fab fa-facebook-f"),
	("fab fa-facebook-messenger","fab fa-facebook-messenger"),
	("fab fa-facebook-square","fab fa-facebook-square"),
	("fas fa-fan","fas fa-fan"),
	("fab fa-fantasy-flight-games","fab fa-fantasy-flight-games"),
	("fas fa-fast-backward","fas fa-fast-backward"),
	("fas fa-fast-forward","fas fa-fast-forward"),
	("fas fa-faucet","fas fa-faucet"),
	("fas fa-fax","fas fa-fax"),
	("fas fa-feather","fas fa-feather"),
	("fas fa-feather-alt","fas fa-feather-alt"),
	("fab fa-fedex","fab fa-fedex"),
	("fas fa-female","fas fa-female"),
	("fas fa-fighter-jet","fas fa-fighter-jet"),
	("fab fa-figma","fab fa-figma"),
	("fas fa-file","fas fa-file"),
	("fas fa-file-alt","fas fa-file-alt"),
	("fas fa-file-archive","fas fa-file-archive"),
	("fas fa-file-audio","fas fa-file-audio"),
	("fas fa-file-code","fas fa-file-code"),
	("fas fa-file-contract","fas fa-file-contract"),
	("fas fa-file-csv","fas fa-file-csv"),
	("fas fa-file-download","fas fa-file-download"),
	("fas fa-file-excel","fas fa-file-excel"),
	("fas fa-file-export","fas fa-file-export"),
	("fas fa-file-image","fas fa-file-image"),
	("fas fa-file-import","fas fa-file-import"),
	("fas fa-file-invoice","fas fa-file-invoice"),
	("fas fa-file-invoice-dollar","fas fa-file-invoice-dollar"),
	("fas fa-file-medical","fas fa-file-medical"),
	("fas fa-file-medical-alt","fas fa-file-medical-alt"),
	("fas fa-file-pdf","fas fa-file-pdf"),
	("fas fa-file-powerpoint","fas fa-file-powerpoint"),
	("fas fa-file-prescription","fas fa-file-prescription"),
	("fas fa-file-signature","fas fa-file-signature"),
	("fas fa-file-upload","fas fa-file-upload"),
	("fas fa-file-video","fas fa-file-video"),
	("fas fa-file-word","fas fa-file-word"),
	("fas fa-fill","fas fa-fill"),
	("fas fa-fill-drip","fas fa-fill-drip"),
	("fas fa-film","fas fa-film"),
	("fas fa-filter","fas fa-filter"),
	("fas fa-fingerprint","fas fa-fingerprint"),
	("fas fa-fire","fas fa-fire"),
	("fab fa-firefox","fab fa-firefox"),
	("fab fa-firefox-browser","fab fa-firefox-browser"),
	("fas fa-first-aid","fas fa-first-aid"),
	("fab fa-first-order","fab fa-first-order"),
	("fab fa-first-order-alt","fab fa-first-order-alt"),
	("fab fa-firstdraft","fab fa-firstdraft"),
	("fas fa-fish","fas fa-fish"),
	("fas fa-fist-raised","fas fa-fist-raised"),
	("fas fa-flag","fas fa-flag"),
	("fas fa-flag-checkered","fas fa-flag-checkered"),
	("fas fa-flag-usa","fas fa-flag-usa"),
	("fas fa-flask","fas fa-flask"),
	("fab fa-flickr","fab fa-flickr"),
	("fab fa-flipboard","fab fa-flipboard"),
	("fas fa-flushed","fas fa-flushed"),
	("fab fa-fly","fab fa-fly"),
	("fas fa-folder","fas fa-folder"),
	("fas fa-folder-minus","fas fa-folder-minus"),
	("fas fa-folder-open","fas fa-folder-open"),
	("fas fa-folder-plus","fas fa-folder-plus"),
	("fas fa-font","fas fa-font"),
	("fab fa-font-awesome","fab fa-font-awesome"),
	("fab fa-font-awesome-alt","fab fa-font-awesome-alt"),
	("fab fa-font-awesome-flag","fab fa-font-awesome-flag"),
	("fas fa-font-awesome-logo-full","fas fa-font-awesome-logo-full"),
	("fab fa-fonticons","fab fa-fonticons"),
	("fab fa-fonticons-fi","fab fa-fonticons-fi"),
	("fas fa-football-ball","fas fa-football-ball"),
	("fab fa-fort-awesome","fab fa-fort-awesome"),
	("fab fa-fort-awesome-alt","fab fa-fort-awesome-alt"),
	("fab fa-forumbee","fab fa-forumbee"),
	("fas fa-forward","fas fa-forward"),
	("fab fa-foursquare","fab fa-foursquare"),
	("fab fa-free-code-camp","fab fa-free-code-camp"),
	("fab fa-freebsd","fab fa-freebsd"),
	("fas fa-frog","fas fa-frog"),
	("fas fa-frown","fas fa-frown"),
	("fas fa-frown-open","fas fa-frown-open"),
	("fab fa-fulcrum","fab fa-fulcrum"),
	("fas fa-funnel-dollar","fas fa-funnel-dollar"),
	("fas fa-futbol","fas fa-futbol"),
	("fab fa-galactic-republic","fab fa-galactic-republic"),
	("fab fa-galactic-senate","fab fa-galactic-senate"),
	("fas fa-gamepad","fas fa-gamepad"),
	("fas fa-gas-pump","fas fa-gas-pump"),
	("fas fa-gavel","fas fa-gavel"),
	("fas fa-gem","fas fa-gem"),
	("fas fa-genderless","fas fa-genderless"),
	("fab fa-get-pocket","fab fa-get-pocket"),
	("fab fa-gg","fab fa-gg"),
	("fab fa-gg-circle","fab fa-gg-circle"),
	("fas fa-ghost","fas fa-ghost"),
	("fas fa-gift","fas fa-gift"),
	("fas fa-gifts","fas fa-gifts"),
	("fab fa-git","fab fa-git"),
	("fab fa-git-alt","fab fa-git-alt"),
	("fab fa-git-square","fab fa-git-square"),
	("fab fa-github","fab fa-github"),
	("fab fa-github-alt","fab fa-github-alt"),
	("fab fa-github-square","fab fa-github-square"),
	("fab fa-gitkraken","fab fa-gitkraken"),
	("fab fa-gitlab","fab fa-gitlab"),
	("fab fa-gitter","fab fa-gitter"),
	("fas fa-glass-cheers","fas fa-glass-cheers"),
	("fas fa-glass-martini","fas fa-glass-martini"),
	("fa fa-glass-martini-alt","fa fa-glass-martini-alt"),
	("fas fa-glass-whiskey","fas fa-glass-whiskey"),
	("fas fa-glasses","fas fa-glasses"),
	("fab fa-glide","fab fa-glide"),
	("fab fa-glide-g","fab fa-glide-g"),
	("fas fa-globe","fas fa-globe"),
	("fas fa-globe-africa","fas fa-globe-africa"),
	("fas fa-globe-americas","fas fa-globe-americas"),
	("fas fa-globe-asia","fas fa-globe-asia"),
	("fas fa-globe-europe","fas fa-globe-europe"),
	("fab fa-gofore","fab fa-gofore"),
	("fas fa-golf-ball","fas fa-golf-ball"),
	("fab fa-goodreads","fab fa-goodreads"),
	("fab fa-goodreads-g","fab fa-goodreads-g"),
	("fab fa-google","fab fa-google"),
	("fab fa-google-drive","fab fa-google-drive"),
	("fab fa-google-play","fab fa-google-play"),
	("fab fa-google-plus","fab fa-google-plus"),
	("fab fa-google-plus-g","fab fa-google-plus-g"),
	("fab fa-google-plus-square","fab fa-google-plus-square"),
	("fab fa-google-wallet","fab fa-google-wallet"),
	("fas fa-gopuram","fas fa-gopuram"),
	("fas fa-graduation-cap","fas fa-graduation-cap"),
	("fab fa-gratipay","fab fa-gratipay"),
	("fab fa-grav","fab fa-grav"),
	("fas fa-greater-than","fas fa-greater-than"),
	("fas fa-greater-than-equal","fas fa-greater-than-equal"),
	("fas fa-grimace","fas fa-grimace"),
	("fas fa-grin","fas fa-grin"),
	("fas fa-grin-alt","fas fa-grin-alt"),
	("fas fa-grin-beam","fas fa-grin-beam"),
	("fas fa-grin-beam-sweat","fas fa-grin-beam-sweat"),
	("fas fa-grin-hearts","fas fa-grin-hearts"),
	("fas fa-grin-squint","fas fa-grin-squint"),
	("fas fa-grin-squint-tears","fas fa-grin-squint-tears"),
	("fas fa-grin-stars","fas fa-grin-stars"),
	("fas fa-grin-tears","fas fa-grin-tears"),
	("fas fa-grin-tongue","fas fa-grin-tongue"),
	("fas fa-grin-tongue-squint","fas fa-grin-tongue-squint"),
	("fas fa-grin-tongue-wink","fas fa-grin-tongue-wink"),
	("fas fa-grin-wink","fas fa-grin-wink"),
	("fas fa-grip-horizontal","fas fa-grip-horizontal"),
	("fas fa-grip-lines","fas fa-grip-lines"),
	("fas fa-grip-lines-vertical","fas fa-grip-lines-vertical"),
	("fas fa-grip-vertical","fas fa-grip-vertical"),
	("fab fa-gripfire","fab fa-gripfire"),
	("fab fa-grunt","fab fa-grunt"),
	("fas fa-guitar","fas fa-guitar"),
	("fab fa-gulp","fab fa-gulp"),
	("fas fa-h-square","fas fa-h-square"),
	("fab fa-hacker-news","fab fa-hacker-news"),
	("fab fa-hacker-news-square","fab fa-hacker-news-square"),
	("fab fa-hackerrank","fab fa-hackerrank"),
	("fas fa-hamburger","fas fa-hamburger"),
	("fas fa-hammer","fas fa-hammer"),
	("fas fa-hamsa","fas fa-hamsa"),
	("fas fa-hand-holding","fas fa-hand-holding"),
	("fas fa-hand-holding-heart","fas fa-hand-holding-heart"),
	("fas fa-hand-holding-medical","fas fa-hand-holding-medical"),
	("fas fa-hand-holding-usd","fas fa-hand-holding-usd"),
	("fas fa-hand-holding-water","fas fa-hand-holding-water"),
	("fas fa-hand-lizard","fas fa-hand-lizard"),
	("fas fa-hand-middle-finger","fas fa-hand-middle-finger"),
	("fas fa-hand-paper","fas fa-hand-paper"),
	("fas fa-hand-peace","fas fa-hand-peace"),
	("fas fa-hand-point-down","fas fa-hand-point-down"),
	("fas fa-hand-point-left","fas fa-hand-point-left"),
	("fas fa-hand-point-right","fas fa-hand-point-right"),
	("fas fa-hand-point-up","fas fa-hand-point-up"),
	("fas fa-hand-pointer","fas fa-hand-pointer"),
	("fas fa-hand-rock","fas fa-hand-rock"),
	("fas fa-hand-scissors","fas fa-hand-scissors"),
	("fas fa-hand-sparkles","fas fa-hand-sparkles"),
	("fas fa-hand-spock","fas fa-hand-spock"),
	("fas fa-hands","fas fa-hands"),
	("fas fa-hands-helping","fas fa-hands-helping"),
	("fas fa-hands-wash","fas fa-hands-wash"),
	("fas fa-handshake","fas fa-handshake"),
	("fas fa-handshake-alt-slash","fas fa-handshake-alt-slash"),
	("fas fa-handshake-slash","fas fa-handshake-slash"),
	("fas fa-hanukiah","fas fa-hanukiah"),
	("fas fa-hard-hat","fas fa-hard-hat"),
	("fas fa-hashtag","fas fa-hashtag"),
	("fas fa-hat-cowboy","fas fa-hat-cowboy"),
	("fas fa-hat-cowboy-side","fas fa-hat-cowboy-side"),
	("fas fa-hat-wizard","fas fa-hat-wizard"),
	("fas fa-hdd","fas fa-hdd"),
	("fas fa-head-side-cough","fas fa-head-side-cough"),
	("fas fa-head-side-cough-slash","fas fa-head-side-cough-slash"),
	("fas fa-head-side-mask","fas fa-head-side-mask"),
	("fas fa-head-side-virus","fas fa-head-side-virus"),
	("fas fa-heading","fas fa-heading"),
	("fas fa-headphones","fas fa-headphones"),
	("fas fa-headphones-alt","fas fa-headphones-alt"),
	("fas fa-headset","fas fa-headset"),
	("fas fa-heart","fas fa-heart"),
	("fas fa-heart-broken","fas fa-heart-broken"),
	("fas fa-heartbeat","fas fa-heartbeat"),
	("fas fa-helicopter","fas fa-helicopter"),
	("fas fa-highlighter","fas fa-highlighter"),
	("fas fa-hiking","fas fa-hiking"),
	("fas fa-hippo","fas fa-hippo"),
	("fab fa-hips","fab fa-hips"),
	("fab fa-hire-a-helper","fab fa-hire-a-helper"),
	("fas fa-history","fas fa-history"),
	("fas fa-hockey-puck","fas fa-hockey-puck"),
	("fas fa-holly-berry","fas fa-holly-berry"),
	("fas fa-home","fas fa-home"),
	("fab fa-hooli","fab fa-hooli"),
	("fab fa-hornbill","fab fa-hornbill"),
	("fas fa-horse","fas fa-horse"),
	("fas fa-horse-head","fas fa-horse-head"),
	("fas fa-hospital","fas fa-hospital"),
	("fas fa-hospital-alt","fas fa-hospital-alt"),
	("fas fa-hospital-symbol","fas fa-hospital-symbol"),
	("fas fa-hospital-user","fas fa-hospital-user"),
	("fas fa-hot-tub","fas fa-hot-tub"),
	("fas fa-hotdog","fas fa-hotdog"),
	("fas fa-hotel","fas fa-hotel"),
	("fab fa-hotjar","fab fa-hotjar"),
	("fas fa-hourglass","fas fa-hourglass"),
	("fas fa-hourglass-end","fas fa-hourglass-end"),
	("fas fa-hourglass-half","fas fa-hourglass-half"),
	("fas fa-hourglass-start","fas fa-hourglass-start"),
	("fas fa-house-damage","fas fa-house-damage"),
	("fas fa-house-user","fas fa-house-user"),
	("fab fa-houzz","fab fa-houzz"),
	("fas fa-hryvnia","fas fa-hryvnia"),
	("fab fa-html5","fab fa-html5"),
	("fab fa-hubspot","fab fa-hubspot"),
	("fas fa-i-cursor","fas fa-i-cursor"),
	("fas fa-ice-cream","fas fa-ice-cream"),
	("fas fa-icicles","fas fa-icicles"),
	("fas fa-icons","fas fa-icons"),
	("fas fa-id-badge","fas fa-id-badge"),
	("fas fa-id-card","fas fa-id-card"),
	("fas fa-id-card-alt","fas fa-id-card-alt"),
	("fab fa-ideal","fab fa-ideal"),
	("fas fa-igloo","fas fa-igloo"),
	("fas fa-image","fas fa-image"),
	("fas fa-images","fas fa-images"),
	("fab fa-imdb","fab fa-imdb"),
	("fas fa-inbox","fas fa-inbox"),
	("fas fa-indent","fas fa-indent"),
	("fas fa-industry","fas fa-industry"),
	("fas fa-infinity","fas fa-infinity"),
	("fas fa-info","fas fa-info"),
	("fas fa-info-circle","fas fa-info-circle"),
	("fab fa-instagram","fab fa-instagram"),
	("fab fa-instagram-square","fab fa-instagram-square"),
	("fab fa-intercom","fab fa-intercom"),
	("fab fa-internet-explorer","fab fa-internet-explorer"),
	("fab fa-invision","fab fa-invision"),
	("fab fa-ioxhost","fab fa-ioxhost"),
	("fas fa-italic","fas fa-italic"),
	("fab fa-itch-io","fab fa-itch-io"),
	("fab fa-itunes","fab fa-itunes"),
	("fab fa-itunes-note","fab fa-itunes-note"),
	("fab fa-java","fab fa-java"),
	("fas fa-jedi","fas fa-jedi"),
	("fab fa-jedi-order","fab fa-jedi-order"),
	("fab fa-jenkins","fab fa-jenkins"),
	("fab fa-jira","fab fa-jira"),
	("fab fa-joget","fab fa-joget"),
	("fas fa-joint","fas fa-joint"),
	("fab fa-joomla","fab fa-joomla"),
	("fab fa-journal-whills","fab fa-journal-whills"),
	("fab fa-js","fab fa-js"),
	("fab fa-js-square","fab fa-js-square"),
	("fab fa-jsfiddle","fab fa-jsfiddle"),
	("fas fa-kaaba","fas fa-kaaba"),
	("fab fa-kaggle","fab fa-kaggle"),
	("fas fa-key","fas fa-key"),
	("fab fa-keybase","fab fa-keybase"),
	("fas fa-keyboard","fas fa-keyboard"),
	("fab fa-keycdn","fab fa-keycdn"),
	("fas fa-khanda","fas fa-khanda"),
	("fab fa-kickstarter","fab fa-kickstarter"),
	("fab fa-kickstarter-k","fab fa-kickstarter-k"),
	("fas fa-kiss","fas fa-kiss"),
	("fas fa-kiss-beam","fas fa-kiss-beam"),
	("fas fa-kiss-wink-heart","fas fa-kiss-wink-heart"),
	("fas fa-kiwi-bird","fas fa-kiwi-bird"),
	("fab fa-korvue","fab fa-korvue"),
	("fas fa-landmark","fas fa-landmark"),
	("fas fa-language","fas fa-language"),
	("fas fa-laptop","fas fa-laptop"),
	("fas fa-laptop-code","fas fa-laptop-code"),
	("fas fa-laptop-house","fas fa-laptop-house"),
	("fas fa-laptop-medical","fas fa-laptop-medical"),
	("fab fa-laravel","fab fa-laravel"),
	("fab fa-lastfm","fab fa-lastfm"),
	("fab fa-lastfm-square","fab fa-lastfm-square"),
	("fas fa-laugh","fas fa-laugh"),
	("fas fa-laugh-beam","fas fa-laugh-beam"),
	("fas fa-laugh-squint","fas fa-laugh-squint"),
	("fas fa-laugh-wink","fas fa-laugh-wink"),
	("fas fa-layer-group","fas fa-layer-group"),
	("fas fa-leaf","fas fa-leaf"),
	("fab fa-leanpub","fab fa-leanpub"),
	("fas fa-lemon","fas fa-lemon"),
	("fab fa-less","fab fa-less"),
	("fas fa-less-than","fas fa-less-than"),
	("fas fa-less-than-equal","fas fa-less-than-equal"),
	("fas fa-level-down-alt","fas fa-level-down-alt"),
	("fas fa-level-up-alt","fas fa-level-up-alt"),
	("fas fa-life-ring","fas fa-life-ring"),
	("fas fa-lightbulb","fas fa-lightbulb"),
	("fab fa-line","fab fa-line"),
	("fas fa-link","fas fa-link"),
	("fab fa-linkedin","fab fa-linkedin"),
	("fab fa-linkedin-in","fab fa-linkedin-in"),
	("fab fa-linode","fab fa-linode"),
	("fab fa-linux","fab fa-linux"),
	("fas fa-lira-sign","fas fa-lira-sign"),
	("fas fa-list","fas fa-list"),
	("fas fa-list-alt","fas fa-list-alt"),
	("fas fa-list-ol","fas fa-list-ol"),
	("fas fa-list-ul","fas fa-list-ul"),
	("fas fa-location-arrow","fas fa-location-arrow"),
	("fas fa-lock","fas fa-lock"),
	("fas fa-lock-open","fas fa-lock-open"),
	("fas fa-long-arrow-alt-down","fas fa-long-arrow-alt-down"),
	("fas fa-long-arrow-alt-left","fas fa-long-arrow-alt-left"),
	("fas fa-long-arrow-alt-right","fas fa-long-arrow-alt-right"),
	("fas fa-long-arrow-alt-up","fas fa-long-arrow-alt-up"),
	("fas fa-low-vision","fas fa-low-vision"),
	("fas fa-luggage-cart","fas fa-luggage-cart"),
	("fas fa-lungs","fas fa-lungs"),
	("fas fa-lungs-virus","fas fa-lungs-virus"),
	("fab fa-lyft","fab fa-lyft"),
	("fab fa-magento","fab fa-magento"),
	("fas fa-magic","fas fa-magic"),
	("fas fa-magnet","fas fa-magnet"),
	("fas fa-mail-bulk","fas fa-mail-bulk"),
	("fab fa-mailchimp","fab fa-mailchimp"),
	("fas fa-male","fas fa-male"),
	("fab fa-mandalorian","fab fa-mandalorian"),
	("fas fa-map","fas fa-map"),
	("fas fa-map-marked","fas fa-map-marked"),
	("fas fa-map-marked-alt","fas fa-map-marked-alt"),
	("fas fa-map-pin","fas fa-map-pin"),
	("fas fa-map-signs","fas fa-map-signs"),
	("fab fa-markdown","fab fa-markdown"),
	("fas fa-marker","fas fa-marker"),
	("fas fa-mars","fas fa-mars"),
	("fas fa-mars-double","fas fa-mars-double"),
	("fas fa-mars-stroke","fas fa-mars-stroke"),
	("fas fa-mars-stroke-h","fas fa-mars-stroke-h"),
	("fas fa-mars-stroke-v","fas fa-mars-stroke-v"),
	("fas fa-mask","fas fa-mask"),
	("fab fa-mastodon","fab fa-mastodon"),
	("fab fa-maxcdn","fab fa-maxcdn"),
	("fab fa-mdb","fab fa-mdb"),
	("fas fa-medal","fas fa-medal"),
	("fab fa-medapps","fab fa-medapps"),
	("fab fa-medium","fab fa-medium"),
	("fab fa-medium-m","fab fa-medium-m"),
	("fas fa-medkit","fas fa-medkit"),
	("fab fa-medrt","fab fa-medrt"),
	("fab fa-meetup","fab fa-meetup"),
	("fab fa-megaport","fab fa-megaport"),
	("fas fa-meh","fas fa-meh"),
	("fas fa-meh-blank","fas fa-meh-blank"),
	("fas fa-meh-rolling-eyes","fas fa-meh-rolling-eyes"),
	("fas fa-memory","fas fa-memory"),
	("fab fa-mendeley","fab fa-mendeley"),
	("fas fa-menorah","fas fa-menorah"),
	("fas fa-mercury","fas fa-mercury"),
	("fas fa-meteor","fas fa-meteor"),
	("fab fa-microblog","fab fa-microblog"),
	("fas fa-microchip","fas fa-microchip"),
	("fas fa-microphone","fas fa-microphone"),
	("fas fa-microphone-alt","fas fa-microphone-alt"),
	("fas fa-microphone-alt-slash","fas fa-microphone-alt-slash"),
	("fas fa-microphone-slash","fas fa-microphone-slash"),
	("fas fa-microscope","fas fa-microscope"),
	("fab fa-microsoft","fab fa-microsoft"),
	("fas fa-minus","fas fa-minus"),
	("fas fa-minus-circle","fas fa-minus-circle"),
	("fas fa-minus-square","fas fa-minus-square"),
	("fas fa-mitten","fas fa-mitten"),
	("fab fa-mix","fab fa-mix"),
	("fab fa-mixcloud","fab fa-mixcloud"),
	("fab fa-mixer","fab fa-mixer"),
	("fab fa-mizuni","fab fa-mizuni"),
	("fas fa-mobile","fas fa-mobile"),
	("fas fa-mobile-alt","fas fa-mobile-alt"),
	("fab fa-modx","fab fa-modx"),
	("fab fa-monero","fab fa-monero"),
	("fas fa-money-bill","fas fa-money-bill"),
	("fas fa-money-bill-alt","fas fa-money-bill-alt"),
	("fas fa-money-bill-wave","fas fa-money-bill-wave"),
	("fas fa-money-bill-wave-alt","fas fa-money-bill-wave-alt"),
	("fas fa-money-check","fas fa-money-check"),
	("fas fa-money-check-alt","fas fa-money-check-alt"),
	("fas fa-monument","fas fa-monument"),
	("fas fa-moon","fas fa-moon"),
	("fas fa-mortar-pestle","fas fa-mortar-pestle"),
	("fas fa-mosque","fas fa-mosque"),
	("fas fa-motorcycle","fas fa-motorcycle"),
	("fas fa-mountain","fas fa-mountain"),
	("fas fa-mouse","fas fa-mouse"),
	("fas fa-mouse-pointer","fas fa-mouse-pointer"),
	("fas fa-mug-hot","fas fa-mug-hot"),
	("fas fa-music","fas fa-music"),
	("fab fa-napster","fab fa-napster"),
	("fab fa-neos","fab fa-neos"),
	("fas fa-network-wired","fas fa-network-wired"),
	("fas fa-neuter","fas fa-neuter"),
	("fas fa-newspaper","fas fa-newspaper"),
	("fab fa-nimblr","fab fa-nimblr"),
	("fab fa-node","fab fa-node"),
	("fab fa-node-js","fab fa-node-js"),
	("fas fa-not-equal","fas fa-not-equal"),
	("fas fa-notes-medical","fas fa-notes-medical"),
	("fab fa-npm","fab fa-npm"),
	("fab fa-ns8","fab fa-ns8"),
	("fab fa-nutritionix","fab fa-nutritionix"),
	("fas fa-object-group","fas fa-object-group"),
	("fas fa-object-ungroup","fas fa-object-ungroup"),
	("fab fa-odnoklassniki","fab fa-odnoklassniki"),
	("fab fa-odnoklassniki-square","fab fa-odnoklassniki-square"),
	("fas fa-oil-can","fas fa-oil-can"),
	("fab fa-old-republic","fab fa-old-republic"),
	("fas fa-om","fas fa-om"),
	("fab fa-opencart","fab fa-opencart"),
	("fab fa-openid","fab fa-openid"),
	("fab fa-opera","fab fa-opera"),
	("fab fa-optin-monster","fab fa-optin-monster"),
	("fab fa-orcid","fab fa-orcid"),
	("fab fa-osi","fab fa-osi"),
	("fas fa-otter","fas fa-otter"),
	("fas fa-outdent","fas fa-outdent"),
	("fab fa-page4","fab fa-page4"),
	("fab fa-pagelines","fab fa-pagelines"),
	("fas fa-pager","fas fa-pager"),
	("fas fa-paint-brush","fas fa-paint-brush"),
	("fas fa-paint-roller","fas fa-paint-roller"),
	("fas fa-palette","fas fa-palette"),
	("fab fa-palfed","fab fa-palfed"),
	("fas fa-pallet","fas fa-pallet"),
	("fas fa-paper-plane","fas fa-paper-plane"),
	("fas fa-paperclip","fas fa-paperclip"),
	("fas fa-parachute-box","fas fa-parachute-box"),
	("fas fa-paragraph","fas fa-paragraph"),
	("fas fa-parking","fas fa-parking"),
	("fas fa-passport","fas fa-passport"),
	("fas fa-pastafarianism","fas fa-pastafarianism"),
	("fas fa-paste","fas fa-paste"),
	("fab fa-patreon","fab fa-patreon"),
	("fas fa-pause","fas fa-pause"),
	("fas fa-pause-circle","fas fa-pause-circle"),
	("fas fa-paw","fas fa-paw"),
	("fab fa-paypal","fab fa-paypal"),
	("fas fa-peace","fas fa-peace"),
	("fas fa-pen","fas fa-pen"),
	("fas fa-pen-alt","fas fa-pen-alt"),
	("fas fa-pen-fancy","fas fa-pen-fancy"),
	("fas fa-pen-nib","fas fa-pen-nib"),
	("fas fa-pen-square","fas fa-pen-square"),
	("fas fa-pencil-alt","fas fa-pencil-alt"),
	("fas fa-pencil-ruler","fas fa-pencil-ruler"),
	("fab fa-penny-arcade","fab fa-penny-arcade"),
	("fas fa-people-arrows","fas fa-people-arrows"),
	("fas fa-people-carry","fas fa-people-carry"),
	("fas fa-pepper-hot","fas fa-pepper-hot"),
	("fas fa-percent","fas fa-percent"),
	("fas fa-percentage","fas fa-percentage"),
	("fab fa-periscope","fab fa-periscope"),
	("fas fa-person-booth","fas fa-person-booth"),
	("fab fa-phabricator","fab fa-phabricator"),
	("fab fa-phoenix-framework","fab fa-phoenix-framework"),
	("fab fa-phoenix-squadron","fab fa-phoenix-squadron"),
	("fas fa-phone","fas fa-phone"),
	("fas fa-phone-alt","fas fa-phone-alt"),
	("fas fa-phone-slash","fas fa-phone-slash"),
	("fas fa-phone-square","fas fa-phone-square"),
	("fas fa-phone-square-alt","fas fa-phone-square-alt"),
	("fas fa-phone-volume","fas fa-phone-volume"),
	("fab fa-photo-video","fab fa-photo-video"),
	("fab fa-php","fab fa-php"),
	("fas fa-pied-piper","fas fa-pied-piper"),
	("fab fa-pied-piper-alt","fab fa-pied-piper-alt"),
	("fab fa-pied-piper-hat","fab fa-pied-piper-hat"),
	("fab fa-pied-piper-pp","fab fa-pied-piper-pp"),
	("fab fa-pied-piper-square","fab fa-pied-piper-square"),
	("fas fa-piggy-bank","fas fa-piggy-bank"),
	("fas fa-pills","fas fa-pills"),
	("fab fa-pinterest","fab fa-pinterest"),
	("fab fa-pinterest-p","fab fa-pinterest-p"),
	("fab fa-pinterest-square","fab fa-pinterest-square"),
	("fas fa-pizza-slice","fas fa-pizza-slice"),
	("fas fa-place-of-worship","fas fa-place-of-worship"),
	("fas fa-plane","fas fa-plane"),
	("fas fa-plane-arrival","fas fa-plane-arrival"),
	("fas fa-plane-departure","fas fa-plane-departure"),
	("fas fa-plane-slash","fas fa-plane-slash"),
	("fas fa-play","fas fa-play"),
	("fas fa-play-circle","fas fa-play-circle"),
	("fab fa-playstation","fab fa-playstation"),
	("fas fa-plug","fas fa-plug"),
	("fas fa-plus","fas fa-plus"),
	("fas fa-plus-circle","fas fa-plus-circle"),
	("fas fa-plus-square","fas fa-plus-square"),
	("fas fa-podcast","fas fa-podcast"),
	("fas fa-poll","fas fa-poll"),
	("fas fa-poll-h","fas fa-poll-h"),
	("fas fa-poo","fas fa-poo"),
	("fas fa-poo-storm","fas fa-poo-storm"),
	("fas fa-poop","fas fa-poop"),
	("fas fa-portrait","fas fa-portrait"),
	("fas fa-pound-sign","fas fa-pound-sign"),
	("fas fa-power-off","fas fa-power-off"),
	("fas fa-pray","fas fa-pray"),
	("fas fa-praying-hands","fas fa-praying-hands"),
	("fas fa-prescription","fas fa-prescription"),
	("fas fa-prescription-bottle","fas fa-prescription-bottle"),
	("fas fa-prescription-bottle-alt","fas fa-prescription-bottle-alt"),
	("fas fa-print","fas fa-print"),
	("fas fa-procedures","fas fa-procedures"),
	("fab fa-product-hunt","fab fa-product-hunt"),
	("fas fa-project-diagram","fas fa-project-diagram"),
	("fas fa-pump-medical","fas fa-pump-medical"),
	("fas fa-pump-soap","fas fa-pump-soap"),
	("fab fa-pushed","fab fa-pushed"),
	("fas fa-puzzle-piece","fas fa-puzzle-piece"),
	("fab fa-python","fab fa-python"),
	("fab fa-qq","fab fa-qq"),
	("fas fa-qrcode","fas fa-qrcode"),
	("fas fa-question","fas fa-question"),
	("fas fa-question-circle","fas fa-question-circle"),
	("fas fa-quidditch","fas fa-quidditch"),
	("fab fa-quinscape","fab fa-quinscape"),
	("fab fa-quora","fab fa-quora"),
	("fas fa-quote-left","fas fa-quote-left"),
	("fas fa-quote-right","fas fa-quote-right"),
	("fas fa-quran","fas fa-quran"),
	("fab fa-r-project","fab fa-r-project"),
	("fas fa-radiation","fas fa-radiation"),
	("fas fa-radiation-alt","fas fa-radiation-alt"),
	("fas fa-rainbow","fas fa-rainbow"),
	("fas fa-random","fas fa-random"),
	("fab fa-raspberry-pi","fab fa-raspberry-pi"),
	("fab fa-ravelry","fab fa-ravelry"),
	("fab fa-react","fab fa-react"),
	("fab fa-reacteurope","fab fa-reacteurope"),
	("fab fa-readme","fab fa-readme"),
	("fab fa-rebel","fab fa-rebel"),
	("fas fa-receipt","fas fa-receipt"),
	("fas fa-record-vinyl","fas fa-record-vinyl"),
	("fas fa-recycle","fas fa-recycle"),
	("fab fa-red-river","fab fa-red-river"),
	("fab fa-reddit","fab fa-reddit"),
	("fab fa-reddit-alien","fab fa-reddit-alien"),
	("fab fa-reddit-square","fab fa-reddit-square"),
	("fab fa-redhat","fab fa-redhat"),
	("fas fa-redo","fas fa-redo"),
	("fas fa-redo-alt","fas fa-redo-alt"),
	("fas fa-registered","fas fa-registered"),
	("fas fa-remove-format","fas fa-remove-format"),
	("fab fa-renren","fab fa-renren"),
	("fas fa-reply","fas fa-reply"),
	("fas fa-reply-all","fas fa-reply-all"),
	("fab fa-replyd","fab fa-replyd"),
	("fas fa-republican","fas fa-republican"),
	("fab fa-researchgate","fab fa-researchgate"),
	("fab fa-resolving","fab fa-resolving"),
	("fas fa-restroom","fas fa-restroom"),
	("fas fa-retweet","fas fa-retweet"),
	("fab fa-rev","fab fa-rev"),
	("fas fa-ribbon","fas fa-ribbon"),
	("fas fa-ring","fas fa-ring"),
	("fas fa-road","fas fa-road"),
	("fas fa-robot","fas fa-robot"),
	("fas fa-rocket","fas fa-rocket"),
	("fab fa-rocketchat","fab fa-rocketchat"),
	("fab fa-rockrms","fab fa-rockrms"),
	("fas fa-route","fas fa-route"),
	("fas fa-rss","fas fa-rss"),
	("fas fa-rss-square","fas fa-rss-square"),
	("fas fa-ruble-sign","fas fa-ruble-sign"),
	("fas fa-ruler","fas fa-ruler"),
	("fas fa-ruler-combined","fas fa-ruler-combined"),
	("fas fa-ruler-horizontal","fas fa-ruler-horizontal"),
	("fas fa-ruler-vertical","fas fa-ruler-vertical"),
	("fas fa-running","fas fa-running"),
	("fas fa-rupee-sign","fas fa-rupee-sign"),
	("fas fa-sad-cry","fas fa-sad-cry"),
	("fas fa-sad-tear","fas fa-sad-tear"),
	("fab fa-safari","fab fa-safari"),
	("fab fa-salesforce","fab fa-salesforce"),
	("fab fa-sass","fab fa-sass"),
	("fas fa-satellite","fas fa-satellite"),
	("fas fa-satellite-dish","fas fa-satellite-dish"),
	("fas fa-save","fas fa-save"),
	("fab fa-schlix","fab fa-schlix"),
	("fas fa-school","fas fa-school"),
	("fas fa-screwdriver","fas fa-screwdriver"),
	("fab fa-scribd","fab fa-scribd"),
	("fas fa-scroll","fas fa-scroll"),
	("fas fa-sd-card","fas fa-sd-card"),
	("fas fa-search","fas fa-search"),
	("fas fa-search-dollar","fas fa-search-dollar"),
	("fas fa-search-location","fas fa-search-location"),
	("fas fa-search-minus","fas fa-search-minus"),
	("fas fa-search-plus","fas fa-search-plus"),
	("fab fa-searchengin","fab fa-searchengin"),
	("fas fa-seedling","fas fa-seedling"),
	("fab fa-sellcast","fab fa-sellcast"),
	("fab fa-sellsy","fab fa-sellsy"),
	("fas fa-server","fas fa-server"),
	("fab fa-servicestack","fab fa-servicestack"),
	("fas fa-shapes","fas fa-shapes"),
	("fas fa-share","fas fa-share"),
	("fas fa-share-alt","fas fa-share-alt"),
	("fas fa-share-alt-square","fas fa-share-alt-square"),
	("fas fa-share-square","fas fa-share-square"),
	("fas fa-shekel-sign","fas fa-shekel-sign"),
	("fas fa-shield-alt","fas fa-shield-alt"),
	("fas fa-shield-virus","fas fa-shield-virus"),
	("fas fa-ship","fas fa-ship"),
	("fas fa-shipping-fast","fas fa-shipping-fast"),
	("fab fa-shirtsinbulk","fab fa-shirtsinbulk"),
	("fas fa-shoe-prints","fas fa-shoe-prints"),
	("fab fa-shopify","fab fa-shopify"),
	("fas fa-shopping-bag","fas fa-shopping-bag"),
	("fas fa-shopping-basket","fas fa-shopping-basket"),
	("fas fa-shopping-cart","fas fa-shopping-cart"),
	("fab fa-shopware","fab fa-shopware"),
	("fas fa-shower","fas fa-shower"),
	("fas fa-shuttle-van","fas fa-shuttle-van"),
	("fas fa-sign","fas fa-sign"),
	("fas fa-sign-in-alt","fas fa-sign-in-alt"),
	("fas fa-sign-language","fas fa-sign-language"),
	("fas fa-sign-out-alt","fas fa-sign-out-alt"),
	("fas fa-signal","fas fa-signal"),
	("fas fa-signature","fas fa-signature"),
	("fas fa-sim-card","fas fa-sim-card"),
	("fab fa-simplybuilt","fab fa-simplybuilt"),
	("fab fa-sistrix","fab fa-sistrix"),
	("fas fa-sitemap","fas fa-sitemap"),
	("fab fa-sith","fab fa-sith"),
	("fas fa-skating","fas fa-skating"),
	("fab fa-sketch","fab fa-sketch"),
	("fas fa-skiing","fas fa-skiing"),
	("fas fa-skiing-nordic","fas fa-skiing-nordic"),
	("fas fa-skull","fas fa-skull"),
	("fas fa-skull-crossbones","fas fa-skull-crossbones"),
	("fab fa-skyatlas","fab fa-skyatlas"),
	("fab fa-skype","fab fa-skype"),
	("fab fa-slack","fab fa-slack"),
	("fab fa-slack-hash","fab fa-slack-hash"),
	("fas fa-slash","fas fa-slash"),
	("fas fa-sleigh","fas fa-sleigh"),
	("fas fa-sliders-h","fas fa-sliders-h"),
	("fab fa-slideshare","fab fa-slideshare"),
	("fas fa-smile","fas fa-smile"),
	("fas fa-smile-beam","fas fa-smile-beam"),
	("fas fa-smile-wink","fas fa-smile-wink"),
	("fas fa-smog","fas fa-smog"),
	("fas fa-smoking","fas fa-smoking"),
	("fas fa-smoking-ban","fas fa-smoking-ban"),
	("fas fa-sms","fas fa-sms"),
	("fab fa-snapchat","fab fa-snapchat"),
	("fab fa-snapchat-ghost","fab fa-snapchat-ghost"),
	("fab fa-snapchat-square","fab fa-snapchat-square"),
	("fas fa-snowboarding","fas fa-snowboarding"),
	("fas fa-snowflake","fas fa-snowflake"),
	("fas fa-snowman","fas fa-snowman"),
	("fas fa-snowplow","fas fa-snowplow"),
	("fas fa-soap","fas fa-soap"),
	("fas fa-socks","fas fa-socks"),
	("fas fa-solar-panel","fas fa-solar-panel"),
	("fas fa-sort","fas fa-sort"),
	("fas fa-sort-alpha-down","fas fa-sort-alpha-down"),
	("fas fa-sort-alpha-down-alt","fas fa-sort-alpha-down-alt"),
	("fas fa-sort-alpha-up","fas fa-sort-alpha-up"),
	("fas fa-sort-alpha-up-alt","fas fa-sort-alpha-up-alt"),
	("fas fa-sort-amount-down","fas fa-sort-amount-down"),
	("fas fa-sort-amount-down-alt","fas fa-sort-amount-down-alt"),
	("fas fa-sort-amount-up","fas fa-sort-amount-up"),
	("fas fa-sort-amount-up-alt","fas fa-sort-amount-up-alt"),
	("fas fa-sort-down","fas fa-sort-down"),
	("fas fa-sort-numeric-down","fas fa-sort-numeric-down"),
	("fas fa-sort-numeric-down-alt","fas fa-sort-numeric-down-alt"),
	("fas fa-sort-numeric-up","fas fa-sort-numeric-up"),
	("fas fa-sort-numeric-up-alt","fas fa-sort-numeric-up-alt"),
	("fas fa-sort-up","fas fa-sort-up"),
	("fab fa-soundcloud","fab fa-soundcloud"),
	("fab fa-sourcetree","fab fa-sourcetree"),
	("fas fa-spa","fas fa-spa"),
	("fas fa-space-shuttle","fas fa-space-shuttle"),
	("fab fa-speakap","fab fa-speakap"),
	("fab fa-speaker-deck","fab fa-speaker-deck"),
	("fas fa-spell-check","fas fa-spell-check"),
	("fas fa-spider","fas fa-spider"),
	("fas fa-spinner","fas fa-spinner"),
	("fas fa-splotch","fas fa-splotch"),
	("fab fa-spotify","fab fa-spotify"),
	("fas fa-spray-can","fas fa-spray-can"),
	("fas fa-square","fas fa-square"),
	("fas fa-square-full","fas fa-square-full"),
	("fas fa-square-root-alt","fas fa-square-root-alt"),
	("fab fa-squarespace","fab fa-squarespace"),
	("fab fa-stack-exchange","fab fa-stack-exchange"),
	("fab fa-stack-overflow","fab fa-stack-overflow"),
	("fab fa-stackpath","fab fa-stackpath"),
	("fas fa-stamp","fas fa-stamp"),
	("fas fa-star","fas fa-star"),
	("fas fa-star-and-crescent","fas fa-star-and-crescent"),
	("fas fa-star-half","fas fa-star-half"),
	("fas fa-star-half-alt","fas fa-star-half-alt"),
	("fas fa-star-of-david","fas fa-star-of-david"),
	("fas fa-star-of-life","fas fa-star-of-life"),
	("fab fa-staylinked","fab fa-staylinked"),
	("fab fa-steam","fab fa-steam"),
	("fab fa-steam-square","fab fa-steam-square"),
	("fab fa-steam-symbol","fab fa-steam-symbol"),
	("fas fa-step-backward","fas fa-step-backward"),
	("fas fa-step-forward","fas fa-step-forward"),
	("fas fa-stethoscope","fas fa-stethoscope"),
	("fab fa-sticker-mule","fab fa-sticker-mule"),
	("fas fa-sticky-note","fas fa-sticky-note"),
	("fas fa-stop","fas fa-stop"),
	("fas fa-stop-circle","fas fa-stop-circle"),
	("fas fa-stopwatch","fas fa-stopwatch"),
	("fas fa-stopwatch-20","fas fa-stopwatch-20"),
	("fas fa-store","fas fa-store"),
	("fas fa-store-alt","fas fa-store-alt"),
	("fas fa-store-alt-slash","fas fa-store-alt-slash"),
	("fas fa-store-slash","fas fa-store-slash"),
	("fab fa-strava","fab fa-strava"),
	("fas fa-stream","fas fa-stream"),
	("fas fa-street-view","fas fa-street-view"),
	("fas fa-strikethrough","fas fa-strikethrough"),
	("fab fa-stripe","fab fa-stripe"),
	("fab fa-stripe-s","fab fa-stripe-s"),
	("fas fa-stroopwafel","fas fa-stroopwafel"),
	("fab fa-studiovinari","fab fa-studiovinari"),
	("fab fa-stumbleupon","fab fa-stumbleupon"),
	("fab fa-stumbleupon-circle","fab fa-stumbleupon-circle"),
	("fas fa-subscript","fas fa-subscript"),
	("fas fa-subway","fas fa-subway"),
	("fas fa-suitcase","fas fa-suitcase"),
	("fas fa-suitcase-rolling","fas fa-suitcase-rolling"),
	("fas fa-sun","fas fa-sun"),
	("fab fa-superpowers","fab fa-superpowers"),
	("fas fa-superscript","fas fa-superscript"),
	("fab fa-supple","fab fa-supple"),
	("fas fa-surprise","fas fa-surprise"),
	("fab fa-suse","fab fa-suse"),
	("fas fa-swatchbook","fas fa-swatchbook"),
	("fab fa-swift","fab fa-swift"),
	("fas fa-swimmer","fas fa-swimmer"),
	("fas fa-swimming-pool","fas fa-swimming-pool"),
	("fab fa-symfony","fab fa-symfony"),
	("fas fa-synagogue","fas fa-synagogue"),
	("fas fa-sync","fas fa-sync"),
	("fas fa-sync-alt","fas fa-sync-alt"),
	("fas fa-syringe","fas fa-syringe"),
	("fas fa-table","fas fa-table"),
	("fas fa-table-tennis","fas fa-table-tennis"),
	("fas fa-tablet","fas fa-tablet"),
	("fas fa-tablet-alt","fas fa-tablet-alt"),
	("fas fa-tablets","fas fa-tablets"),
	("fas fa-tachometer-alt","fas fa-tachometer-alt"),
	("fas fa-tag","fas fa-tag"),
	("fas fa-tags","fas fa-tags"),
	("fas fa-tape","fas fa-tape"),
	("fas fa-tasks","fas fa-tasks"),
	("fas fa-taxi","fas fa-taxi"),
	("fab fa-teamspeak","fab fa-teamspeak"),
	("fas fa-teeth","fas fa-teeth"),
	("fas fa-teeth-open","fas fa-teeth-open"),
	("fab fa-telegram","fab fa-telegram"),
	("fab fa-telegram-plane","fab fa-telegram-plane"),
	("fas fa-temperature-high","fas fa-temperature-high"),
	("fas fa-temperature-low","fas fa-temperature-low"),
	("fab fa-tencent-weibo","fab fa-tencent-weibo"),
	("fas fa-tenge","fas fa-tenge"),
	("fas fa-terminal","fas fa-terminal"),
	("fas fa-text-height","fas fa-text-height"),
	("fas fa-text-width","fas fa-text-width"),
	("fas fa-th","fas fa-th"),
	("fas fa-th-large","fas fa-th-large"),
	("fas fa-th-list","fas fa-th-list"),
	("fab fa-the-red-yeti","fab fa-the-red-yeti"),
	("fas fa-theater-masks","fas fa-theater-masks"),
	("fab fa-themeco","fab fa-themeco"),
	("fab fa-themeisle","fab fa-themeisle"),
	("fas fa-thermometer","fas fa-thermometer"),
	("fas fa-thermometer-empty","fas fa-thermometer-empty"),
	("fas fa-thermometer-full","fas fa-thermometer-full"),
	("fas fa-thermometer-half","fas fa-thermometer-half"),
	("fas fa-thermometer-quarter","fas fa-thermometer-quarter"),
	("fas fa-thermometer-three-quarters","fas fa-thermometer-three-quarters"),
	("fab fa-think-peaks","fab fa-think-peaks"),
	("fas fa-thumbs-down","fas fa-thumbs-down"),
	("fas fa-thumbs-up","fas fa-thumbs-up"),
	("fas fa-thumbtack","fas fa-thumbtack"),
	("fas fa-ticket-alt","fas fa-ticket-alt"),
	("fas fa-times","fas fa-times"),
	("fas fa-times-circle","fas fa-times-circle"),
	("fas fa-tint","fas fa-tint"),
	("fas fa-tint-slash","fas fa-tint-slash"),
	("fas fa-tired","fas fa-tired"),
	("fas fa-toggle-off","fas fa-toggle-off"),
	("fas fa-toggle-on","fas fa-toggle-on"),
	("fas fa-toilet","fas fa-toilet"),
	("fas fa-toilet-paper","fas fa-toilet-paper"),
	("fas fa-toilet-paper-slash","fas fa-toilet-paper-slash"),
	("fas fa-toolbox","fas fa-toolbox"),
	("fas fa-tools","fas fa-tools"),
	("fas fa-tooth","fas fa-tooth"),
	("fas fa-torah","fas fa-torah"),
	("fas fa-torii-gate","fas fa-torii-gate"),
	("fas fa-tractor","fas fa-tractor"),
	("fab fa-trade-federation","fab fa-trade-federation"),
	("fas fa-trademark","fas fa-trademark"),
	("fas fa-traffic-light","fas fa-traffic-light"),
	("fas fa-trailer","fas fa-trailer"),
	("fas fa-train","fas fa-train"),
	("fas fa-tram","fas fa-tram"),
	("fas fa-transgender","fas fa-transgender"),
	("fas fa-transgender-alt","fas fa-transgender-alt"),
	("fas fa-trash","fas fa-trash"),
	("fas fa-trash-alt","fas fa-trash-alt"),
	("fas fa-trash-restore","fas fa-trash-restore"),
	("fas fa-trash-restore-alt","fas fa-trash-restore-alt"),
	("fas fa-tree","fas fa-tree"),
	("fab fa-trello","fab fa-trello"),
	("fab fa-tripadvisor","fab fa-tripadvisor"),
	("fas fa-trophy","fas fa-trophy"),
	("fas fa-truck","fas fa-truck"),
	("fas fa-truck-loading","fas fa-truck-loading"),
	("fas fa-truck-monster","fas fa-truck-monster"),
	("fas fa-truck-moving","fas fa-truck-moving"),
	("fas fa-truck-pickup","fas fa-truck-pickup"),
	("fas fa-tshirt","fas fa-tshirt"),
	("fas fa-tty","fas fa-tty"),
	("fab fa-tumblr","fab fa-tumblr"),
	("fab fa-tumblr-square","fab fa-tumblr-square"),
	("fas fa-tv","fas fa-tv"),
	("fab fa-twitch","fab fa-twitch"),
	("fab fa-twitter","fab fa-twitter"),
	("fab fa-twitter-square","fab fa-twitter-square"),
	("fab fa-typo3","fab fa-typo3"),
	("fab fa-uber","fab fa-uber"),
	("fab fa-ubuntu","fab fa-ubuntu"),
	("fab fa-uikit","fab fa-uikit"),
	("fab fa-umbraco","fab fa-umbraco"),
	("fas fa-umbrella","fas fa-umbrella"),
	("fas fa-umbrella-beach","fas fa-umbrella-beach"),
	("fas fa-underline","fas fa-underline"),
	("fas fa-undo","fas fa-undo"),
	("fas fa-undo-alt","fas fa-undo-alt"),
	("fab fa-uniregistry","fab fa-uniregistry"),
	("fab fa-unity","fab fa-unity"),
	("fas fa-universal-access","fas fa-universal-access"),
	("fas fa-university","fas fa-university"),
	("fas fa-unlink","fas fa-unlink"),
	("fas fa-unlock","fas fa-unlock"),
	("fas fa-unlock-alt","fas fa-unlock-alt"),
	("fab fa-untappd","fab fa-untappd"),
	("fas fa-upload","fas fa-upload"),
	("fab fa-ups","fab fa-ups"),
	("fab fa-usb","fab fa-usb"),
	("fas fa-user","fas fa-user"),
	("fas fa-user-alt","fas fa-user-alt"),
	("fas fa-user-alt-slash","fas fa-user-alt-slash"),
	("fas fa-user-astronaut","fas fa-user-astronaut"),
	("fas fa-user-check","fas fa-user-check"),
	("fas fa-user-circle","fas fa-user-circle"),
	("fas fa-user-clock","fas fa-user-clock"),
	("fas fa-user-cog","fas fa-user-cog"),
	("fas fa-user-edit","fas fa-user-edit"),
	("fas fa-user-friends","fas fa-user-friends"),
	("fas fa-user-graduate","fas fa-user-graduate"),
	("fas fa-user-injured","fas fa-user-injured"),
	("fas fa-user-lock","fas fa-user-lock"),
	("fas fa-user-md","fas fa-user-md"),
	("fas fa-user-minus","fas fa-user-minus"),
	("fas fa-user-ninja","fas fa-user-ninja"),
	("fas fa-user-nurse","fas fa-user-nurse"),
	("fas fa-user-plus","fas fa-user-plus"),
	("fas fa-user-secret","fas fa-user-secret"),
	("fas fa-user-shield","fas fa-user-shield"),
	("fas fa-user-slash","fas fa-user-slash"),
	("fas fa-user-tag","fas fa-user-tag"),
	("fas fa-user-tie","fas fa-user-tie"),
	("fas fa-user-times","fas fa-user-times"),
	("fas fa-users","fas fa-users"),
	("fas fa-users-cog","fas fa-users-cog"),
	("fab fa-usps","fab fa-usps"),
	("fab fa-ussunnah","fab fa-ussunnah"),
	("fas fa-utensil-spoon","fas fa-utensil-spoon"),
	("fas fa-utensils","fas fa-utensils"),
	("fab fa-vaadin","fab fa-vaadin"),
	("fas fa-vector-square","fas fa-vector-square"),
	("fas fa-venus","fas fa-venus"),
	("fas fa-venus-double","fas fa-venus-double"),
	("fas fa-venus-mars","fas fa-venus-mars"),
	("fab fa-viacoin","fab fa-viacoin"),
	("fab fa-viadeo","fab fa-viadeo"),
	("fab fa-viadeo-square","fab fa-viadeo-square"),
	("fas fa-vial","fas fa-vial"),
	("fas fa-vials","fas fa-vials"),
	("fab fa-viber","fab fa-viber"),
	("fas fa-video","fas fa-video"),
	("fas fa-video-slash","fas fa-video-slash"),
	("fas fa-vihara","fas fa-vihara"),
	("fab fa-vimeo","fab fa-vimeo"),
	("fab fa-vimeo-v","fab fa-vimeo-v"),
	("fab fa-vine","fab fa-vine"),
	("fas fa-virus","fas fa-virus"),
	("fas fa-virus-slash","fas fa-virus-slash"),
	("fas fa-viruses","fas fa-viruses"),
	("fab fa-vk","fab fa-vk"),
	("fab fa-vnv","fab fa-vnv"),
	("fas fa-voicemail","fas fa-voicemail"),
	("fas fa-volleyball-ball","fas fa-volleyball-ball"),
	("fas fa-volume-down","fas fa-volume-down"),
	("fas fa-volume-mute","fas fa-volume-mute"),
	("fas fa-volume-off","fas fa-volume-off"),
	("fas fa-volume-up","fas fa-volume-up"),
	("fas fa-vote-yea","fas fa-vote-yea"),
	("fas fa-vr-cardboard","fas fa-vr-cardboard"),
	("fab fa-vuejs","fab fa-vuejs"),
	("fas fa-walking","fas fa-walking"),
	("fas fa-wallet","fas fa-wallet"),
	("fas fa-warehouse","fas fa-warehouse"),
	("fas fa-water","fas fa-water"),
	("fas fa-wave-square","fas fa-wave-square"),
	("fab fa-waze","fab fa-waze"),
	("fab fa-weebly","fab fa-weebly"),
	("fab fa-weibo","fab fa-weibo"),
	("fas fa-weight","fas fa-weight"),
	("fas fa-weight-hanging","fas fa-weight-hanging"),
	("fab fa-weixin","fab fa-weixin"),
	("fab fa-whatsapp","fab fa-whatsapp"),
	("fab fa-whatsapp-square","fab fa-whatsapp-square"),
	("fas fa-wheelchair","fas fa-wheelchair"),
	("fab fa-whmcs","fab fa-whmcs"),
	("fas fa-wifi","fas fa-wifi"),
	("fab fa-wikipedia-w","fab fa-wikipedia-w"),
	("fas fa-wind","fas fa-wind"),
	("fas fa-window-close","fas fa-window-close"),
	("fas fa-window-maximize","fas fa-window-maximize"),
	("fas fa-window-minimize","fas fa-window-minimize"),
	("fas fa-window-restore","fas fa-window-restore"),
	("fab fa-windows","fab fa-windows"),
	("fas fa-wine-bottle","fas fa-wine-bottle"),
	("fas fa-wine-glass","fas fa-wine-glass"),
	("fas fa-wine-glass-alt","fas fa-wine-glass-alt"),
	("fab fa-wix","fab fa-wix"),
	("fab fa-wizards-of-the-coast","fab fa-wizards-of-the-coast"),
	("fab fa-wolf-pack-battalion","fab fa-wolf-pack-battalion"),
	("fas fa-won-sign","fas fa-won-sign"),
	("fab fa-wordpress","fab fa-wordpress"),
	("fab fa-wordpress-simple","fab fa-wordpress-simple"),
	("fab fa-wpbeginner","fab fa-wpbeginner"),
	("fab fa-wpexplorer","fab fa-wpexplorer"),
	("fab fa-wpforms","fab fa-wpforms"),
	("fab fa-wpressr","fab fa-wpressr"),
	("fas fa-wrench","fas fa-wrench"),
	("fas fa-x-ray","fas fa-x-ray"),
	("fab fa-xbox","fab fa-xbox"),
	("fab fa-xing","fab fa-xing"),
	("fab fa-xing-square","fab fa-xing-square"),
	("fab fa-y-combinator","fab fa-y-combinator"),
	("fab fa-yahoo","fab fa-yahoo"),
	("fab fa-yammer","fab fa-yammer"),
	("fab fa-yandex","fab fa-yandex"),
	("fab fa-yandex-international","fab fa-yandex-international"),
	("fab fa-yarn","fab fa-yarn"),
	("fab fa-yelp","fab fa-yelp"),
	("fas fa-yen-sign","fas fa-yen-sign"),
	("fas fa-yin-yang","fas fa-yin-yang"),
	("fab fa-yoast","fab fa-yoast"),
	("fab fa-youtube","fab fa-youtube"),
	("fab fa-youtube-square","fab fa-youtube-square"),
]


COLOR_CHOICES = [
	('none', 'Transparent'),
	('#d9bf77', 'Brand Color'),
	('#000000', 'black'),
	('#ffffff', 'white'),
	('#6610f2', 'indigo'),
	('#007bff', 'primary'),
	('#6c757d', 'secondary'),
	('#28a745', 'success'),
	('#17a2b8', 'info'),
	('#ffc107', 'warning'),
	('#dc3545', 'danger'),
	('#343a40', 'dark'),
	('lime', 'fluorescent'),
	('#ffebee', '1 red lighten-4'),
	('#ffcdd2', '2 red lighten-3'),
	('#ef9a9a', '3 red lighten-2'),
	('#e57373', '4 red lighten-1'),
	('#f44336', '5 red'),
	('red', '6 deep red'),
	('#e53935', '7 red darken-1'),
	('#d32f2f', '8 red darken-2'),
	('#c62828', '9 red darken-3'),
	('#b71c1c', '10 red darken-4'),
	('#ff8a80', '11 red accent-1'),
	('#ff5252', '12 red accent-2'),
	('#ff1744', '13 red accent-3'),
	('#d50000', '14 red accent-4'),
	('#fce4ec', '15 pink lighten-5'),
	('#f8bbd0', '16 pink lighten-4'),
	('#f48fb1', '17 pink lighten-3'),
	('#f06292', '18 pink lighten-2'),
	('#ec407a', '19 pink lighten-1'),
	('#e91e63', '20 pink'),
	('#d81b60', '21 pink darken-1'),
	('#c2185b', '22 pink darken-2'),
	('#ad1457', '23 pink darken-3'),
	('#880e4f', '24 pink darken-4'),
	('#ff80ab', '25 pink accent-1'),
	('#ff4081', '26 pink accent-2'),
	('#f50057', '27 pink accent-3'),
	('#c51162', '28 pink accent-4'),
	('#f3e5f5', '29 purple lighten-5'),
	('#e1bee7', '30 purple lighten-4'),
	('#ce93d8', '31 purple lighten-3'),
	('#ba68c8', '32 purple lighten-2'),
	('#ab47bc', '33 purple lighten-1'),
	('#9c27b0', '34 purple'),
	('#8e24aa', '35 purple darken-1'),
	('#7b1fa2', '36 purple darken-2'),
	('#6a1b9a', '37 purple darken-3'),
	('#4a148c', '38 purple darken-4'),
	('#ea80fc', '39 purple accent-1'),
	('#e040fb', '40 purple accent-2'),
	('#d500f9', '41 purple accent-3'),
	('#aa00ff', '42 purple accent-4'),
	('#ede7f6', '43 deep-purple lighten-5'),
	('#d1c4e9', '44 deep-purple lighten-4'),
	('#b39ddb', '45 deep-purple lighten-3'),
	('#9575cd', '46 deep-purple lighten-2'),
	('#7e57c2', '47 deep-purple lighten-1'),
	('#673ab7', '48 deep-purple'),
	('#5e35b1', '49 deep-purple darken-1'),
	('#512da8', '50 deep-purple darken-2'),
	('#4527a0', '51 deep-purple darken-3'),
	('#311b92', '52 deep-purple darken-4'),
	('#b388ff', '53 deep-purple accent-1'),
	('#7c4dff', '54 deep-purple accent-2'),
	('#651fff', '55 deep-purple accent-3'),
	('#6200ea', '56 deep-purple accent-4'),
	('#e8eaf6', '57 indigo lighten-5'),
	('#c5cae9', '58 indigo lighten-4'),
	('#9fa8da', '59 indigo lighten-3'),
	('#7986cb', '60 indigo lighten-2'),
	('#5c6bc0', '61 indigo lighten-1'),
	('#3f51b5', '62 indigo'),
	('#3949ab', '63 indigo darken-1'),
	('#303f9f', '64 indigo darken-2'),
	('#283593', '65 indigo darken-3'),
	('#1a237e', '66 indigo darken-4'),
	('#8c9eff', '67 indigo accent-1'),
	('#536dfe', '68 indigo accent-2'),
	('#3d5afe', '69 indigo accent-3'),
	('#304ffe', '70 indigo accent-4'),
	('#e3f2fd', '71 blue lighten-5'),
	('#bbdefb', '72 blue lighten-4'),
	('#90caf9', '79 blue lighten-3'),
	('#64b5f6', '74 blue lighten-2'),
	('#42a5f5', '75 blue lighten-1'),
	('#2196f3', '76 blue'),
	('#1e88e5', '77 blue darken-1'),
	('#1976d2', '78 blue darken-2'),
	('#1565c0', '79 blue darken-3'),
	('#0d47a1', '80 blue darken-4'),
	('#82b1ff', '81 blue accent-1'),
	('#448aff', '82 blue accent-2'),
	('#2979ff', '83 blue accent-3'),
	('#2962ff', '84 blue accent-4'),
	('#e1f5fe', '85 light-blue lighten-5'),
	('#b3e5fc', '86 light-blue lighten-4'),
	('#81d4fa', '87 light-blue lighten-3'),
	('#4fc3f7', '88 light-blue lighten-2'),
	('#29b6f6', '89 light-blue lighten-1'),
	('#03a9f4', '90 light-blue'),
	('#039be5', '91 light-blue darken-1'),
	('#0288d1', '92 light-blue darken-2'),
	('#0277bd', '93 light-blue darken-3'),
	('#01579b', '94 light-blue darken-4'),
	('#80d8ff', '95 light-blue accent-1'),
	('#40c4ff', '96 light-blue accent-2'),
	('#00b0ff', '97 light-blue accent-3'),
	('#0091ea', '98 light-blue accent-4'),
	('#e0f7fa', '99 cyan lighten-5'),
	('#b2ebf2', '100 cyan lighten-4'),
	('#80deea', '101 cyan lighten-3'),
	('#4dd0e1', '102 cyan lighten-2'),
	('#26c6da', '103 cyan lighten-1'),
	('#00bcd4', '104 cyan'),
	('#00acc1', '105 cyan darken-1'),
	('#0097a7', '106 cyan darken-2'),
	('#00838f', '107 cyan darken-3'),
	('#006064', '108 cyan darken-4'),
	('#84ffff', '109 cyan accent-1'),
	('#18ffff', '110 cyan accent-2'),
	('#00e5ff', '111 cyan accent-3'),
	('#00b8d4', '112 cyan accent-4'),
	('#e0f2f1', '113 teal lighten-5'),
	('#b2dfdb', '114 teal lighten-4'),
	('#80cbc4', '115 teal lighten-3'),
	('#4db6ac', '116 teal lighten-2'),
	('#26a69a', '117 teal lighten-1'),
	('#009688', '118 teal'),
	('#00897b', '119 teal darken-1'),
	('#00796b', '120 teal darken-2'),
	('#00695c', '121 teal darken-3'),
	('#004d40', '122 teal darken-4'),
	('#a7ffeb', '123 teal accent-1'),
	('#64ffda', '124 teal accent-2'),
	('#1de9b6', '125 teal accent-3'),
	('#00bfa5', '126 teal accent-4'),
	('#e8f5e9', '127 green lighten-5'),
	('#c8e6c9', '128 green lighten-4'),
	('#a5d6a7', '129 green lighten-3'),
	('#81c784', '130 green lighten-2'),
	('#66bb6a', '131 green lighten-1'),
	('#4caf50', '132 green'),
	('#43a047', '133 green darken-1'),
	('#388e3c', '134 green darken-2'),
	('#2e7d32', '135 green darken-3'),
	('#1b5e20', '136 green darken-4'),
	('#b9f6ca', '137 green accent-1'),
	('#69f0ae', '138 green accent-2'),
	('#00e676', '139 green accent-3'),
	('#00c853', '140 green accent-4'),
	('#f1f8e9', '141 light-green lighten-5'),
	('#dcedc8', '142 light-green lighten-4'),
	('#c5e1a5', '143 light-green lighten-3'),
	('#aed581', '144 light-green lighten-2'),
	('#9ccc65', '145 light-green lighten-1'),
	('#8bc34a', '146 light-green'),
	('#7cb342', '147 light-green darken-1'),
	('#689f38', '148 light-green darken-2'),
	('#558b2f', '149 light-green darken-3'),
	('#33691e', '150 light-green darken-4'),
	('#ccff90', '151 light-green accent-1'),
	('#b2ff59', '152 light-green accent-2'),
	('#76ff03', '153 light-green accent-3'),
	('#64dd17', '154 light-green accent-4'),
	('#f9fbe7', '155 lime lighten-5'),
	('#f0f4c3', '156 lime lighten-4'),
	('#e6ee9c', '157 lime lighten-3'),
	('#dce775', '158 lime lighten-2'),
	('#d4e157', '159 lime lighten-1'),
	('#cddc39', '160 lime'),
	('#c0ca33', '161 lime darken-1'),
	('#afb42b', '162 lime darken-2'),
	('#9e9d24', '163 lime darken-3'),
	('#827717', '164 lime darken-4'),
	('#f4ff81', '165 lime accent-1'),
	('#eeff41', '166 lime accent-2'),
	('#c6ff00', '167 lime accent-3'),
	('#aeea00', '168 lime accent-4'),
	('#fffde7', '169 yellow lighten-5'),
	('#fff9c4', '170 yellow lighten-4'),
	('#fff59d', '171 yellow lighten-3'),
	('#fff176', '172 yellow lighten-2'),
	('#ffee58', '173 yellow lighten-1'),
	('#ffeb3b', '174 yellowx'),
	('#fdd835', '175 yellow darken-1'),
	('#fbc02d', '176 yellow darken-2'),
	('#f9a825', '177 yellow darken-3'),
	('#f57f17', '178 yellow darken-4'),
	('#ffff8d', '179 yellow accent-1'),
	('#ffff00', '180 yellow accent-2'),
	('#ffea00', '181 yellow accent-3'),
	('#ffd600', '182 yellow accent-4'),
	('#fff8e1', '183 amber lighten-5'),
	('#ffecb3', '184 amber lighten-4'),
	('#ffe082', '185 amber lighten-3'),
	('#ffd54f', '186 amber lighten-2'),
	('#ffca28', '187 amber lighten-1'),
	('#ffc107', '188 amber'),
	('#ffb300', '189 amber darken-1'),
	('#ffa000', '190 amber darken-2'),
	('#ff8f00', '191 amber darken-3'),
	('#ff6f00', '192 amber darken-4'),
	('#ffe57f', '193 amber accent-1'),
	('#ffd740', '194 amber accent-2'),
	('#ffc400', '195 amber accent-3'),
	('#ffab00', '196 amber accent-4'),
	('#fff3e0', '197 orange lighten-5'),
	('#ffe0b2', '198 orange lighten-4'),
	('#ffcc80', '199 orange lighten-3'),
	('#ffb74d', '200 orange lighten-2'),
	('#ffa726', '201 orange lighten-1'),
	('#ff9800', '202 orange'),
	('#fb8c00', '203 orange darken-1'),
	('#f57c00', '204 orange darken-2'),
	('#ef6c00', '205 orange darken-3'),
	('#e65100', '206 orange darken-4'),
	('#ffd180', '207 orange accent-1'),
	('#ffab40', '208 orange accent-2'),
	('#ff9100', '209 orange accent-3'),
	('#ff6d00', '210 orange accent-4'),
	##################################
	('#ff8a65', '211 deep-orange lighten-2'),
	('#ff7043', '212 deep-orange lighten-1'),
	('#ff5722', '213 deep-orange'),
	('#f4511e', '214 deep-orange darken-1'),
	('#e64a19', '215 deep-orange darken-2'),
	('#d84315', '216 deep-orange darken-3'),
	('#bf360c', '217 deep-orange darken-4'),
	('#ff9e80', '218 deep-orange accent-1'),
	('#ff6e40', '219 deep-orange accent-2'),
	('#ff3d00', '220 deep-orange accent-3'),
	('#dd2c00', '221 deep-orange accent-4'),
	('#efebe9', '222 brown lighten-5'),
	('#d7ccc8', '223 brown lighten-4'),
	('#bcaaa4', '224 brown lighten-3'),
	('#a1887f', '225 brown lighten-2'),
	('#8d6e63', '226 brown lighten-1'),
	('#795548', '227 brown'),
	('#6d4c41', '228 brown darken-1'),
	('#5d4037', '229 brown darken-2'),
	('#4e342e', '230 brown darken-3'),
	('#3e2723', '231 brown darken-4'),
	('#fafafa', '232 grey lighten-5'),
	('#f5f5f5', '233 grey lighten-4'),
	('#eeeeee', '234 grey lighten-3'),
	('#e0e0e0', '235 grey lighten-2'),
	('#bdbdbd', '236 grey lighten-1'),
	('#9e9e9e', '237 grey'),
	('#757575', '238 grey darken-1'),
	('#616161', '239 grey darken-2'),
	('#424242', '240 grey darken-3'),
	('#212121', '241 grey darken-4'),
	('#cfd8dc', '242 blue-grey lighten-4'),
	('#b0bec5', '243 blue-grey lighten-3'),
	('#90a4ae', '244 blue-grey lighten-2'),
	('#78909c', '245 blue-grey lighten-1'),
	('#607d8b', '246 blue-grey'),
	('#546e7a', '247 blue-grey darken-1'),
	('#455a64', '248 blue-grey darken-2'),
	('#37474f', '249 blue-grey darken-3'),
	('#263238', '250 blue-grey darken-4'),
]


'''
ICON_CHOICES_EN_DELETE = [
	('address-book', 'address book'),
	('address-card', 'address card'),
	('fab fa-airbnb', 'airbnb'),
	('amazon', 'amazon'),
	('amazon-pay', 'amazon pay'),
	('anchor', 'anchor'),
	('android', 'android'),
	('angellist', 'angellist'),
	('angular', 'angular'),
	('app-store', 'app-store'),
	('app-store-ios', 'app-store-ios'),
	('apple', 'apple'),
	('apple-pay', 'apple-pay'),
	('artstation', 'artstation'),
	('asterisk', 'asterisk'),
	('at', 'at'),
	('atlas', 'atlas'),
	('atom', 'atom'),
	('audible', 'audible'),
	('award', 'award'),
	('aws', 'aws'),
	('baby', 'baby'),
	('baby-carriage', 'baby-carriage'),
	('bacon', 'bacon'),
	('bahai', 'bahai'),
	('balance-scale', 'balance-scale'),
	('balance-scale-left', 'balance-scale-left'),
	('balance-scale-right', 'balance-scale-right'),
	('ban', 'ban'),
	('band-aid', 'band-aid'),
	('barcode', 'barcode'),
	('bars', 'bars'),
	('basketball-ball', 'basketball-ball'),
	('bath', 'bath'),
	('battery-empty', 'battery-empty'),
	('battery-half', 'battery-half'),
	('battery-full', 'battery-full'),
	('bed', 'bed'),
	('beer', 'beer'),
	('bell', 'bell'),
	('bell-slash', 'bell-slash'),
	('bible', 'bible'),
	('bicycle', 'bicycle'),
	('biking', 'biking'),
	('biohazard', 'biohazard'),
	('bitcoin', 'bitcoin'),
	('blender', 'blender'),
	('blind', 'blind'),
	('blog', 'blog'),
	('bluetooth', 'bluetooth'),
	('bluetooth-b', 'bluetooth-b'),
	('bolt', 'bolt'),
	('bomb', 'bomb'),
	('book', 'book'),
	('book-dead', 'book-dead'),
	('book-medical', 'book-medical'),
	('book-open', 'book-open'),
	('book-reader', 'book-reader'),
	('bookmark', 'bookmark'),
	('bong', 'bong'),
	('bootstrap', 'bootstrap'),
	('border-all', 'border-all'),
	('bowling-ball', 'bowling-ball'),
	('box', 'box'),
	('box-open', 'box-open'),
	('boxes', 'boxes'),
	('braille', 'braille'),
	('brain', 'brain'),
	('briefcase', 'briefcase'),
	('briefcase-medical', 'briefcase-medical'),
	('broadcast-tower', 'broadcast-tower'),
	('brush', 'brush'),
	('btc', 'btc'),
	('buffer', 'buffer'),
	('bug', 'bug'),
	('bullhorn', 'bullhorn'),
	('bullseye', 'bullseye'),
	('burn', 'burn'),
	('bus', 'bus'),
	('calculator', 'calculator'),
	('calendar-alt', 'calendar-alt'),
	('calendar-check', 'calendar-check'),
	('calendar-minus', 'calendar-minus'),
	('calendar-plus', 'calendar-plus'),
	('calendar-times', 'calendar-times'),
	('camera', 'camera'),
	('camera-retro', 'camera-retro'),
	('canadian-maple-leaf', 'canadian-maple-leaf'),
	('candy-cane', 'candy-cane'),
	('cannabis', 'cannabis'),
	('capsules', 'capsules'),
	('car', 'car'),
	('car-battery', 'car-battery'),
	('caravan', 'caravan'),
	('caret-square-down', 'caret-square-down'),
	('caret-square-left', 'caret-square-left'),
	('caret-square-right', 'caret-square-right'),
	('caret-square-up', 'caret-square-up'),
	('carrot', 'carrot'),
	('cart-arrow-down', 'cart-arrow-down'),
	('cart-plus', 'cart-plus'),
	('cash-register', 'cash-register'),
	('cat', 'cat'),
	('cc-discover', 'cc-discover'),
	('cc-mastercard', 'cc-mastercard'),
	('cc-paypal', 'cc-paypal'),
	('cc-stripe', 'cc-stripe'),
	('cc-visa', 'cc-visa'),
	('chalkboard', 'chalkboard'),
	('chalkboard-teacher', 'chalkboard-teacher'),
	('chart-bar', 'chart-bar'),
	('chart-line', 'chart-line'),
	('check', 'check'),
	('check-circle', 'check-circle'),
	('check-square', 'check-square'),
	('chess', 'chess'),
	('chess-king', 'chess-king'),
	('chess-queen', 'chess-queen'),
	('chevron-circle-down', 'chevron-circle-down'),
	('chevron-circle-left', 'chevron-circle-left'),
	('chevron-circle-right', 'chevron-circle-right'),
	('chevron-circle-up', 'chevron-circle-up'),
	('chromecast', 'chromecast'),
	('church', 'church'),
	('circle', 'circle'),
	('circle-notch', 'circle-notch'),
	('clinic-medical', 'clinic-medical'),
	('clipboard', 'clipboard'),
	('clipboard-check', 'clipboard-check'),
	('clipboard-list', 'clipboard-list'),
	('clone', 'clone'),
	('cloud-download-alt', 'cloud-download-alt'),
	('cloud-upload-alt', 'cloud-upload-alt'),
	('cloudscale', 'cloudscale'),
	('cocktail', 'cocktail'),
	('code', 'code'),
	('code-branch', 'code-branch'),
	('coffee', 'coffee'),
	('cog', 'cog'),
	('cogs', 'cogs'),
	('coins', 'coins'),
	('comment-dollar', 'comment-dollar'),
	('comments', 'comments'),
	('concierge-bell', 'concierge-bell'),
	('cookie-bite', 'cookie-bite'),
	('couch', 'couch'),
	('cpanel', 'cpanel'),
	('creative-commons', 'creative-commons'),
	('creative-commons-by', 'creative-commons-by'),
	('credit-card', 'credit-card'),
	('cross', 'cross'),
	('crosshairs', 'crosshairs'),
	('crown', 'crown'),
	('cube', 'cube'),
	('cubes', 'cubes'),
	('cut', 'cut'),
	('database', 'database'),
	('desktop', 'desktop'),
	('diaspora', 'diaspora'),
	('dice', 'dice'),
	('dice-d20', 'dice-d20'),
	('dice-d6', 'dice-d6'),
	('divide', 'divide'),
	('dizzy', 'dizzy'),
	('dna', 'dna'),
	('docker', 'docker'),
	('dog', 'dog'),
	('dollar-sign', 'dollar-sign'),
	('dolly', 'dolly'),
	('dove', 'dove'),
	('download', 'download'),
	('dropbox', 'dropbox'),
	('drumstick-bite', 'drumstick-bite'),
	('ellipsis-h', 'ellipsis-h'),
	('ellipsis-v', 'ellipsis-v'),
	('empire', 'empire'),
	('envelope', 'envelope'),
	('envelope-open', 'envelope-open'),
	('envelope-open-text', 'envelope-open-text'),
	('envelope-square', 'envelope-square'),
	('envira', 'envira'),
	('equals', 'equals'),
	('eraser', 'eraser'),
	('ethereum', 'ethereum'),
	('ethernet', 'ethernet'),
	('euro-sign', 'euro-sign'),
	('exchange-alt', 'exchange-alt'),
	('exclamation-circle', 'exclamation-circle'),
	('exclamation-triangle', 'exclamation-triangle'),
	('expand', 'expand'),
	('expeditedssl', 'expeditedssl'),
	('eye', 'eye'),
	('eye-slash', 'eye-slash'),
	('facebook', 'facebook'),
	('facebook-messenger', 'facebook-messenger'),
	('fan', 'fan'),
	('feather-alt', 'feather-alt'),
	('female', 'female'),
	('fighter-jet', 'fighter-jet'),
	('file-alt', 'file-alt'),
	('film', 'film'),
	('filter', 'filter'),
	('fish', 'fish'),
	('flushed', 'flushed'),
	('fly', 'fly'),
	('folder', 'folder'),
	('folder-open', 'folder-open'),
	('frog', 'frog'),
	('frown', 'frown'),
	('frown-open', 'frown-open'),
	('funnel-dollar', 'funnel-dollar'),
	('futbol', 'futbol'),
	('gamepad', 'gamepad'),
	('gas-pump', 'gas-pump'),
	('gem', 'gem'),
	('gift', 'gift'),
]


ICON_CHOICES_ES = [
	('address-book', 'libro de direcciones'),
	('address-card', 'tarjeta de direcciones'),
	('airbnb', 'airbnb'),
	('amazon', 'amazon'),
	('amazon-pay', 'amazon pay'),
	('anchor', 'ancla'),
	('android', 'android'),
	('angellist', 'viva'),
	('angular', 'angular'),
	('app-store', 'app store'),
	('app-store-ios', 'app store ios'),
	('apple', 'apple'),
	('apple-pay', 'apple-pay'),
	('artstation', 'artstation'),
	('asterisk', 'asterisco'),
	('at', 'arroba'),
	('atlas', 'atlas'),
	('atom', 'atomo'),
	('audible', 'audible'),
	('award', 'award'),
	('aws', 'aws'),
	('baby', 'bebé'),
	('baby-carriage', 'bebé en coche'),
	('bacon', 'bacon'),
	('bahai', 'bahai'),
	('balance-scale', 'balanza'),
	('balance-scale-left', 'balanza a la izquierda'),
	('balance-scale-right', 'balanza a la derecha'),
	('ban', 'ban'),
	('band-aid', 'band aid'),
	('barcode', 'código de barras'),
	('bars', 'barras'),
	('basketball-ball', 'balón de basketball'),
	('bath', 'bath'),
	('battery-empty', 'batería vacía'),
	('battery-half', 'battería medias'),
	('battery-full', 'battería llena'),
	('bed', 'cama'),
	('beer', 'cerveza'),
	('bell', 'campana'),
	('bell-slash', 'campana silente'),
	('bible', 'biblia'),
	('bicycle', 'bicicleta'),
	('biking', 'ciclista'),
	('biohazard', 'biopeligroso'),
	('bitcoin', 'bitcoin'),

	('blender', 'blender'),
	('blind', 'blind'),
	('blog', 'blog'),
	('bluetooth', 'bluetooth'),
	('bluetooth-b', 'bluetooth b'),
	('bolt', 'voltaje'),
	('bomb', 'bomba'),
	('book', 'libro'),
	('book-dead', 'libro y calavera'),
	('book-medical', 'libro y medicina'),
	('book-open', 'libro abierto'),
	('book-reader', 'lector'),
	('bookmark', 'bookmark'),
	('bong', 'bong'),
	('bootstrap', 'bootstrap'),
	('border-all', 'border-all'),
	('bowling-ball', 'bowling-ball'),
	('box', 'box'),
	('box-open', 'box-open'),
	('boxes', 'boxes'),
	('braille', 'braille'),
	('brain', 'brain'),
	('briefcase', 'briefcase'),
	('briefcase-medical', 'briefcase-medical'),
	('broadcast-tower', 'broadcast-tower'),
	('brush', 'brush'),
	('btc', 'btc'),
	('buffer', 'buffer'),
	('bug', 'bug'),
	('bullhorn', 'bullhorn'),
	('bullseye', 'bullseye'),
	('burn', 'burn'),
	('bus', 'bus'),
	('calculator', 'calculator'),
	('calendar-alt', 'calendar-alt'),
	('calendar-check', 'calendar-check'),
	('calendar-minus', 'calendar-minus'),
	('calendar-plus', 'calendar-plus'),
	('calendar-times', 'calendar-times'),
	('camera', 'camera'),
	('camera-retro', 'camera-retro'),
	('canadian-maple-leaf', 'canadian-maple-leaf'),
	('candy-cane', 'candy-cane'),
	('cannabis', 'cannabis'),
	('capsules', 'capsules'),
	('car', 'car'),
	('car-battery', 'car-battery'),
	('caravan', 'caravan'),
	('caret-square-down', 'caret-square-down'),
	('caret-square-left', 'caret-square-left'),
	('caret-square-right', 'caret-square-right'),
	('caret-square-up', 'caret-square-up'),
	('carrot', 'carrot'),
	('cart-arrow-down', 'cart-arrow-down'),
	('cart-plus', 'cart-plus'),
	('cash-register', 'cash-register'),
	('cat', 'cat'),
	('cc-discover', 'cc-discover'),
	('cc-mastercard', 'cc-mastercard'),
	('cc-paypal', 'cc-paypal'),
	('cc-stripe', 'cc-stripe'),
	('cc-visa', 'cc-visa'),
	('chalkboard', 'chalkboard'),
	('chalkboard-teacher', 'chalkboard-teacher'),
	('chart-bar', 'chart-bar'),
	('chart-line', 'chart-line'),
	('check', 'check'),
	('check-circle', 'check-circle'),
	('check-square', 'check-square'),
	('chess', 'chess'),
	('chess-king', 'chess-king'),
	('chess-queen', 'chess-queen'),
	('chevron-circle-down', 'chevron-circle-down'),
	('chevron-circle-left', 'chevron-circle-left'),
	('chevron-circle-right', 'chevron-circle-right'),
	('chevron-circle-up', 'chevron-circle-up'),
	('chromecast', 'chromecast'),
	('church', 'church'),
	('circle', 'circle'),
	('circle-notch', 'circle-notch'),
	('clinic-medical', 'clinic-medical'),
	('clipboard', 'clipboard'),
	('clipboard-check', 'clipboard-check'),
	('clipboard-list', 'clipboard-list'),
	('clone', 'clone'),
	('cloud-download-alt', 'cloud-download-alt'),
	('cloud-upload-alt', 'cloud-upload-alt'),
	('cloudscale', 'cloudscale'),
	('cocktail', 'cocktail'),
	('code', 'code'),
	('code-branch', 'code-branch'),
	('coffee', 'coffee'),
	('cog', 'cog'),
	('cogs', 'cogs'),
	('coins', 'coins'),
	('comment-dollar', 'comment-dollar'),
	('comments', 'comments'),
	('concierge-bell', 'concierge-bell'),
	('cookie-bite', 'cookie-bite'),
	('couch', 'couch'),
	('cpanel', 'cpanel'),
	('creative-commons', 'creative-commons'),
	('creative-commons-by', 'creative-commons-by'),
	('credit-card', 'credit-card'),
	('cross', 'cross'),
	('crosshairs', 'crosshairs'),
	('crown', 'crown'),
	('cube', 'cube'),
	('cubes', 'cubes'),
	('cut', 'cut'),
	('database', 'database'),
	('desktop', 'desktop'),
	('diaspora', 'diaspora'),
	('dice', 'dice'),
	('dice-d20', 'dice-d20'),
	('dice-d6', 'dice-d6'),
	('divide', 'divide'),
	('dizzy', 'dizzy'),
	('dna', 'dna'),
	('docker', 'docker'),
	('dog', 'dog'),
	('dollar-sign', 'dollar-sign'),
	('dolly', 'dolly'),
	('dove', 'dove'),
	('download', 'download'),
	('dropbox', 'dropbox'),
	('drumstick-bite', 'drumstick-bite'),
	('ellipsis-h', 'ellipsis-h'),
	('ellipsis-v', 'ellipsis-v'),
	('empire', 'empire'),
	('envelope', 'envelope'),
	('envelope-open', 'envelope-open'),
	('envelope-open-text', 'envelope-open-text'),
	('envelope-square', 'envelope-square'),
	('envira', 'envira'),
	('equals', 'equals'),
	('eraser', 'eraser'),
	('ethereum', 'ethereum'),
	('ethernet', 'ethernet'),
	('euro-sign', 'euro-sign'),
	('exchange-alt', 'exchange-alt'),
	('exclamation-circle', 'exclamation-circle'),
	('exclamation-triangle', 'exclamation-triangle'),
	('expand', 'expand'),
	('expeditedssl', 'expeditedssl'),
	('eye', 'eye'),
	('eye-slash', 'eye-slash'),
	('facebook', 'facebook'),
	('facebook-messenger', 'facebook-messenger'),
	('fan', 'fan'),
	('feather-alt', 'feather-alt'),
	('female', 'female'),
	('fighter-jet', 'fighter-jet'),
	('file-alt', 'file-alt'),
	('film', 'film'),
	('filter', 'filter'),
	('fish', 'fish'),
	('flushed', 'flushed'),
	('fly', 'fly'),
	('folder', 'folder'),
	('folder-open', 'folder-open'),
	('frog', 'frog'),
	('frown', 'frown'),
	('frown-open', 'frown-open'),
	('funnel-dollar', 'funnel-dollar'),
	('futbol', 'futbol'),
	('gamepad', 'gamepad'),
	('gas-pump', 'gas-pump'),
	('gem', 'gem'),
	('gift', 'gift'),
]
'''